/**
 * SEO Sync Controller — BlueAgle
 * Exposes API endpoints that drive the SEO Sync Engine.
 * All endpoints require verifyAdminToken + SEO permission.
 */

const { runSeoSync, STATIC_PAGES } = require('../services/seoSyncEngine');
const { SeoSetting, SeoAuditLog, Product, Category, SubCategory } = require('../models');
const { Op } = require('sequelize');

// POST /api/seo/sync/generate
// Generate missing SEO records (safe, idempotent, does not overwrite manual edits)
const generateMissingSeo = async (req, res) => {
    try {
        const triggeredBy = req.user?.email || 'admin';
        const report = await runSeoSync({
            onlyMissing: true,
            overwriteAuto: false,
            skipManual: true,
            dryRun: false,
            triggeredBy,
        });

        await SeoAuditLog.create({
            pageKey: '__SYNC__',
            action: 'SYNC_GENERATE_MISSING',
            performedBy: triggeredBy,
            changes: {
                scanned: report.scanned,
                created: report.created,
                skipped: report.skipped,
                skippedManual: report.skippedManual,
                executionTimeMs: report.executionTimeMs,
            },
        });

        res.json({
            success: true,
            message: `SEO sync complete. Created ${report.created} new records.`,
            report,
        });
    } catch (err) {
        console.error('[SEO Sync] generateMissingSeo error:', err);
        res.status(500).json({ success: false, message: err.message });
    }
};

// POST /api/seo/sync/regenerate
// Regenerate SEO with options passed in body
// body: { onlyMissing, overwriteAuto, skipManual, dryRun }
const regenerateSeo = async (req, res) => {
    try {
        const {
            onlyMissing = false,
            overwriteAuto = true,
            skipManual = true,
            dryRun = false,
        } = req.body;

        const triggeredBy = req.user?.email || 'admin';
        const report = await runSeoSync({
            onlyMissing,
            overwriteAuto,
            skipManual,
            dryRun,
            triggeredBy,
        });

        if (!dryRun) {
            await SeoAuditLog.create({
                pageKey: '__SYNC__',
                action: 'SYNC_REGENERATE',
                performedBy: triggeredBy,
                changes: {
                    scanned: report.scanned,
                    created: report.created,
                    updated: report.updated,
                    skipped: report.skipped,
                    skippedManual: report.skippedManual,
                    executionTimeMs: report.executionTimeMs,
                    options: { onlyMissing, overwriteAuto, skipManual, dryRun },
                },
            });
        }

        res.json({
            success: true,
            dryRun,
            message: dryRun
                ? `Dry run complete. Would create ${report.created}, update ${report.updated}, skip ${report.skipped}.`
                : `Regeneration complete. Created ${report.created}, updated ${report.updated}.`,
            report,
        });
    } catch (err) {
        console.error('[SEO Sync] regenerateSeo error:', err);
        res.status(500).json({ success: false, message: err.message });
    }
};

// GET /api/seo/sync/preview
// Dry-run preview — shows what would be created/updated without touching DB
const previewSync = async (req, res) => {
    try {
        const report = await runSeoSync({
            onlyMissing: true,
            overwriteAuto: false,
            skipManual: true,
            dryRun: true,
            triggeredBy: req.user?.email || 'preview',
        });

        res.json({ success: true, report });
    } catch (err) {
        res.status(500).json({ success: false, message: err.message });
    }
};

// GET /api/seo/sync/missing
// Returns list of pages that have no SEO record yet
const getMissingPages = async (req, res) => {
    try {
        const report = await runSeoSync({
            onlyMissing: true,
            dryRun: true,
            triggeredBy: 'check',
        });

        const missing = report.pages.filter(p => p.action === 'CREATE');
        res.json({
            success: true,
            totalMissing: missing.length,
            totalScanned: report.scanned,
            pages: missing,
        });
    } catch (err) {
        res.status(500).json({ success: false, message: err.message });
    }
};

// GET /api/seo/sync/stats
// Returns dashboard statistics for SEO sync panel
const getSyncStats = async (req, res) => {
    try {
        const total = await SeoSetting.count();
        const autoGenerated = await SeoSetting.count({ where: { isAutoGenerated: true } });
        const manuallyEdited = await SeoSetting.count({ where: { isManuallyEdited: true } });
        const indexed = await SeoSetting.count({ where: { isIndexed: true } });
        const noIndex = await SeoSetting.count({ where: { isIndexed: false } });

        // Count by page type
        const byType = await SeoSetting.findAll({
            attributes: ['pageType', [require('sequelize').fn('COUNT', require('sequelize').col('id')), 'count']],
            group: ['pageType'],
            raw: true,
        });

        // Scan to find how many pages are missing
        const missingReport = await runSeoSync({ onlyMissing: true, dryRun: true, triggeredBy: 'stats' });
        const missingCount = missingReport.pages.filter(p => p.action === 'CREATE').length;

        // Recent sync logs
        const recentLogs = await SeoAuditLog.findAll({
            where: { action: { [Op.in]: ['SYNC_GENERATE_MISSING', 'SYNC_REGENERATE', 'AUTO_SYNC_CREATE', 'AUTO_SYNC_UPDATE'] } },
            order: [['createdAt', 'DESC']],
            limit: 10,
        });

        res.json({
            success: true,
            stats: {
                total,
                autoGenerated,
                manuallyEdited,
                indexed,
                noIndex,
                missingCount,
                byType,
            },
            recentLogs,
        });
    } catch (err) {
        res.status(500).json({ success: false, message: err.message });
    }
};

// POST /api/seo/sync/mark-manual/:id
// Mark a record as manually edited (prevents auto-sync overwrite)
const markAsManual = async (req, res) => {
    try {
        const { id } = req.params;
        const record = await SeoSetting.findByPk(id);
        if (!record) return res.status(404).json({ message: 'SEO record not found' });

        await record.update({ isManuallyEdited: true, updatedBy: req.user?.email || 'admin' });
        res.json({ success: true, message: 'Marked as manually edited. Auto-sync will skip this record.' });
    } catch (err) {
        res.status(500).json({ success: false, message: err.message });
    }
};

// DELETE /api/seo/sync/mark-manual/:id
// Unmark manual edit (allows auto-sync to update again)
const unmarkManual = async (req, res) => {
    try {
        const { id } = req.params;
        const record = await SeoSetting.findByPk(id);
        if (!record) return res.status(404).json({ message: 'SEO record not found' });

        await record.update({ isManuallyEdited: false, updatedBy: req.user?.email || 'admin' });
        res.json({ success: true, message: 'Manual edit flag cleared. Auto-sync can now update this record.' });
    } catch (err) {
        res.status(500).json({ success: false, message: err.message });
    }
};

module.exports = {
    generateMissingSeo,
    regenerateSeo,
    previewSync,
    getMissingPages,
    getSyncStats,
    markAsManual,
    unmarkManual,
};
