const {
    sequelize, Product, SubCategory, Category,
    ProductHighlight, ProductSpecification, ProductBadge,
    ProductCertification, ProductNutrition
} = require('../models');

const PRODUCTS_DATA = [
    // ─── CATEGORY 7: COLD PRESSED OILS ──────────────────────────────────────────
    // Subcategory 7: Groundnut Oil
    {
        name: "Cold Pressed Groundnut Oil - 500ml",
        slug: "cold-pressed-groundnut-oil-500ml",
        shortName: "Cold Pressed Groundnut 500ml",
        sku: "BAG-CPO-GNO-500M",
        barcode: "8901234500701",
        subCategoryId: 7,
        brand: "BlueAgle",
        shortDescription: "Traditional cold pressed groundnut oil extracted under low heat to retain natural nuttiness.",
        description: "BlueAgle Cold Pressed Groundnut Oil is extracted from premium quality sun-dried peanuts using traditional expeller methods. Processed without chemical solvent extraction or high-heat refining, it preserves natural antioxidants, vitamin E, and authentic groundnut aroma.",
        price: 190.00,
        mrp: 230.00,
        costPrice: 150.00,
        gstPercentage: 5.00,
        taxStatus: "Taxable",
        weight: "500ml",
        stock: 120,
        lowStockAlert: 10,
        minOrderQuantity: 1,
        maxOrderQuantity: 15,
        trackInventory: true,
        stockStatus: "In Stock",
        warehouseLocation: "A1-R01",
        images: [],
        videoUrl: null,
        isFeatured: true,
        isNewArrival: false,
        isBestSeller: true,
        isRecommended: true,
        isTrending: false,
        status: "Published",
        visibility: "Public",
        rating: 4.8,
        reviewCount: 95,
        viewCount: 1420,
        tags: ["Cold Pressed", "Groundnut Oil", "Natural", "Cooking Oil"],
        ingredients: ["100% Raw Groundnut Kernels"],
        benefits: ["Suitable for everyday sautéing and deep frying", "High smoke point for traditional recipes", "Rich natural peanut aroma"],
        usageInstructions: ["Use for everyday Indian cooking and frying", "Store in a cool, dry place away from direct sunlight", "Seal bottle cap securely after each use"],
        deliveryTime: "2-4 Days",
        shippingMethod: "Standard Delivery",
        codAvailable: true,
        expressDelivery: true,
        returnEligible: true,
        replacementEligible: true,
        metaTitle: "Cold Pressed Groundnut Oil 500ml | BlueAgle Natural Oils",
        metaDescription: "Buy pure BlueAgle Cold Pressed Groundnut Oil 500ml online. Unrefined peanut oil ideal for healthy daily cooking.",
        metaKeywords: "cold pressed groundnut oil 500ml, peanut oil, unrefined cooking oil, blueagle oil",
        customAttributes: { extractionMethod: "Cold Expeller Pressed", packagingType: "Food Grade PET Bottle", origin: "India" },
        highlights: [
            { icon: "FaLeaf", title: "100% Unrefined", description: "Zero chemical refining or bleaching agent added.", sortOrder: 1 },
            { icon: "FaFire", title: "High Smoke Point", description: "Ideal for deep frying, sautéing, and daily Indian dishes.", sortOrder: 2 },
            { icon: "FaShieldAlt", title: "Sun-Dried Peanuts", description: "Made strictly from handpicked premium grade groundnuts.", sortOrder: 3 }
        ],
        specifications: [
            { groupName: "General Information", specKey: "Extraction Temperature", specValue: "Below 45°C", sortOrder: 1 },
            { groupName: "Packaging", specKey: "Net Volume", specValue: "500 ml", sortOrder: 2 },
            { groupName: "Shelf Life", specKey: "Expiry", specValue: "9 Months from packaging", sortOrder: 3 }
        ],
        badges: [{ badgeText: "Bestseller", color: "#ff3269", icon: "FaStar", sortOrder: 1 }]
    },
    {
        name: "Cold Pressed Groundnut Oil - 1L",
        slug: "cold-pressed-groundnut-oil-1l",
        shortName: "Cold Pressed Groundnut 1L",
        sku: "BAG-CPO-GNO-1L",
        barcode: "8901234500702",
        subCategoryId: 7,
        brand: "BlueAgle",
        shortDescription: "Pure cold pressed unrefined groundnut oil in convenient 1-liter bottle.",
        description: "Crafted for health-conscious kitchens, BlueAgle Cold Pressed Groundnut Oil 1L brings deep nutty flavor and authentic kitchen aroma to your meals. Extracted mechanically without heat treatment.",
        price: 360.00,
        mrp: 432.00,
        costPrice: 280.00,
        gstPercentage: 5.00,
        taxStatus: "Taxable",
        weight: "1L",
        stock: 210,
        lowStockAlert: 15,
        minOrderQuantity: 1,
        maxOrderQuantity: 20,
        trackInventory: true,
        stockStatus: "In Stock",
        warehouseLocation: "A1-R02",
        images: [],
        videoUrl: null,
        isFeatured: true,
        isNewArrival: false,
        isBestSeller: true,
        isRecommended: true,
        isTrending: true,
        status: "Published",
        visibility: "Public",
        rating: 4.9,
        reviewCount: 142,
        viewCount: 2850,
        tags: ["Cold Pressed", "Groundnut Oil", "1 Litre", "Daily Cooking"],
        ingredients: ["100% Pure Groundnut Kernels"],
        benefits: ["Preserves natural aroma and taste", "Rich in healthy monounsaturated fats", "Great for deep frying and tempering"],
        usageInstructions: ["Ideal for all Indian curries, stir-fries, and gravies", "Keep in a cool dry pantry", "Recap tightly after opening"],
        deliveryTime: "2-4 Days",
        shippingMethod: "Standard Delivery",
        codAvailable: true,
        expressDelivery: true,
        returnEligible: true,
        replacementEligible: true,
        metaTitle: "Cold Pressed Groundnut Oil 1L | BlueAgle Natural Oils",
        metaDescription: "Order BlueAgle Cold Pressed Groundnut Oil 1L. Unrefined peanut oil for daily healthy cooking delivered to your home.",
        metaKeywords: "cold pressed groundnut oil 1l, peanut oil 1 litre, unrefined oil, blueagle groundnut oil",
        customAttributes: { extractionMethod: "Cold Expeller Pressed", packagingType: "Food Grade Bottle", origin: "India" },
        highlights: [
            { icon: "FaLeaf", title: "Cold Processed", description: "Preserves natural flavor and authentic aroma.", sortOrder: 1 },
            { icon: "FaCheck", title: "No Preservatives", description: "Free from artificial chemicals and anti-foaming agents.", sortOrder: 2 }
        ],
        specifications: [
            { groupName: "Product Info", specKey: "Volume", specValue: "1 Litre", sortOrder: 1 },
            { groupName: "Product Info", specKey: "Processing", specValue: "Mechanical Cold Pressing", sortOrder: 2 }
        ],
        badges: [{ badgeText: "Popular", color: "#3c006b", icon: "FaFire", sortOrder: 1 }]
    },
    {
        name: "Cold Pressed Groundnut Oil - 5L Can",
        slug: "cold-pressed-groundnut-oil-5l",
        shortName: "Cold Pressed Groundnut 5L",
        sku: "BAG-CPO-GNO-5L",
        barcode: "8901234500703",
        subCategoryId: 7,
        brand: "BlueAgle",
        shortDescription: "Family economy 5-liter can of unrefined cold pressed groundnut cooking oil.",
        description: "Economical 5L bulk container of BlueAgle Cold Pressed Groundnut Oil designed for large families and heavy cooking requirements. Freshly cold pressed from selected oilseed groundnuts.",
        price: 1750.00,
        mrp: 2100.00,
        costPrice: 1400.00,
        gstPercentage: 5.00,
        taxStatus: "Taxable",
        weight: "5L",
        stock: 45,
        lowStockAlert: 5,
        minOrderQuantity: 1,
        maxOrderQuantity: 5,
        trackInventory: true,
        stockStatus: "In Stock",
        warehouseLocation: "A1-R03",
        images: [],
        videoUrl: null,
        isFeatured: false,
        isNewArrival: false,
        isBestSeller: false,
        isRecommended: true,
        isTrending: false,
        status: "Published",
        visibility: "Public",
        rating: 4.7,
        reviewCount: 38,
        viewCount: 650,
        tags: ["Cold Pressed", "Groundnut Oil", "5 Litre Can", "Family Pack"],
        ingredients: ["100% Pure Selected Peanuts"],
        benefits: ["Bulk savings for household cooking", "High thermal stability", "Traditional unrefined quality"],
        usageInstructions: ["Refill smaller kitchen bottles as needed", "Store in shade away from direct sunlight", "Ensure lid seal is tightly closed"],
        deliveryTime: "3-5 Days",
        shippingMethod: "Heavy Cargo Delivery",
        codAvailable: true,
        expressDelivery: false,
        returnEligible: true,
        replacementEligible: true,
        metaTitle: "Cold Pressed Groundnut Oil 5L Can | BlueAgle Bulk Oils",
        metaDescription: "Buy BlueAgle Cold Pressed Groundnut Oil 5L economy jar. Pure unrefined peanut oil for family kitchens.",
        metaKeywords: "groundnut oil 5l can, cold pressed peanut oil 5 litres, bulk cooking oil, blueagle",
        customAttributes: { extractionMethod: "Cold Expeller Pressed", packagingType: "Heavy Duty HDPE Can", origin: "India" },
        highlights: [
            { icon: "FaBoxes", title: "Family Economy Can", description: "Best value pack for large households and regular cooking.", sortOrder: 1 }
        ],
        specifications: [
            { groupName: "Packaging", specKey: "Container Type", specValue: "HDPE Handle Can", sortOrder: 1 },
            { groupName: "General", specKey: "Net Volume", specValue: "5 Litres", sortOrder: 2 }
        ],
        badges: [{ badgeText: "Value Saver", color: "#059669", icon: "FaTag", sortOrder: 1 }]
    },

    // Subcategory 8: Coconut Oil
    {
        name: "Cold Pressed Coconut Oil - 500ml",
        slug: "cold-pressed-coconut-oil-500ml",
        shortName: "Cold Pressed Coconut 500ml",
        sku: "BAG-CPO-CNO-500M",
        barcode: "8901234500801",
        subCategoryId: 8,
        brand: "BlueAgle",
        shortDescription: "Pure cold pressed oil extracted from sun-dried sulphur-free copra.",
        description: "BlueAgle Cold Pressed Coconut Oil is crafted from hand-picked sun-dried coconut copra. Naturally extracted without chemical bleaching or high-temperature processing, preserving rich coconut aroma and medium-chain fatty acids.",
        price: 220.00,
        mrp: 264.00,
        costPrice: 175.00,
        gstPercentage: 5.00,
        taxStatus: "Taxable",
        weight: "500ml",
        stock: 140,
        lowStockAlert: 10,
        minOrderQuantity: 1,
        maxOrderQuantity: 15,
        trackInventory: true,
        stockStatus: "In Stock",
        warehouseLocation: "A2-R01",
        images: [],
        videoUrl: null,
        isFeatured: true,
        isNewArrival: false,
        isBestSeller: true,
        isRecommended: true,
        isTrending: true,
        status: "Published",
        visibility: "Public",
        rating: 4.8,
        reviewCount: 110,
        viewCount: 1980,
        tags: ["Coconut Oil", "Cold Pressed", "Copra Oil", "Edible & Hair Care"],
        ingredients: ["100% Sun-Dried Coconut Copra"],
        benefits: ["Versatile for cooking, baking, and dietary use", "Distinct natural coconut fragrance", "Free from added mineral oils or synthetic fragrance"],
        usageInstructions: ["Use for South Indian cooking, tempering, and frying", "May solidify below 24°C; place in warm water to liquefy", "Store in a dry location"],
        deliveryTime: "2-4 Days",
        shippingMethod: "Standard Delivery",
        codAvailable: true,
        expressDelivery: true,
        returnEligible: true,
        replacementEligible: true,
        metaTitle: "Cold Pressed Coconut Oil 500ml | BlueAgle Pure Oils",
        metaDescription: "Buy pure BlueAgle Cold Pressed Coconut Oil 500ml. Extracted from sulphur-free copra for kitchen & wellness.",
        metaKeywords: "cold pressed coconut oil 500ml, copra oil, natural coconut oil, blueagle coconut oil",
        customAttributes: { extractionMethod: "Cold Pressed", packagingType: "Wide-Mouth Food Grade Jar", origin: "India" },
        highlights: [
            { icon: "FaLeaf", title: "Sulphur-Free Copra", description: "Made from clean, sun-dried natural coconut copra.", sortOrder: 1 },
            { icon: "FaSmile", title: "Multi-Purpose", description: "Ideal for culinary preparation and traditional self-care.", sortOrder: 2 }
        ],
        specifications: [
            { groupName: "Product Info", specKey: "Solidification Temp", specValue: "Below 24°C (Natural Phase Change)", sortOrder: 1 },
            { groupName: "Volume", specKey: "Net Content", specValue: "500 ml", sortOrder: 2 }
        ],
        badges: [{ badgeText: "Pure Copra", color: "#0284c7", icon: "FaCheck", sortOrder: 1 }]
    },
    {
        name: "Cold Pressed Coconut Oil - 1L",
        slug: "cold-pressed-coconut-oil-1l",
        shortName: "Cold Pressed Coconut 1L",
        sku: "BAG-CPO-CNO-1L",
        barcode: "8901234500802",
        subCategoryId: 8,
        brand: "BlueAgle",
        shortDescription: "1-liter bottle of traditional unrefined cold pressed coconut oil.",
        description: "Enjoy the authentic taste of coastal Indian cuisine with BlueAgle Cold Pressed Coconut Oil 1L. Carefully cold-extracted from dried coconut kernels, ensuring natural golden hue and mild sweet aroma.",
        price: 420.00,
        mrp: 500.00,
        costPrice: 330.00,
        gstPercentage: 5.00,
        taxStatus: "Taxable",
        weight: "1L",
        stock: 180,
        lowStockAlert: 15,
        minOrderQuantity: 1,
        maxOrderQuantity: 20,
        trackInventory: true,
        stockStatus: "In Stock",
        warehouseLocation: "A2-R02",
        images: [],
        videoUrl: null,
        isFeatured: false,
        isNewArrival: false,
        isBestSeller: true,
        isRecommended: true,
        isTrending: false,
        status: "Published",
        visibility: "Public",
        rating: 4.9,
        reviewCount: 135,
        viewCount: 2400,
        tags: ["Coconut Oil", "Cold Pressed", "1 Litre", "Natural Cooking"],
        ingredients: ["100% Pure Coconut Kernel Copra"],
        benefits: ["Authentic coastal culinary flavor", "Contains natural lauric acid", "Zero chemical refining"],
        usageInstructions: ["Suitable for daily cooking, roasting, and salad dressings", "Store at room temperature", "Keep cap closed tight"],
        deliveryTime: "2-4 Days",
        shippingMethod: "Standard Delivery",
        codAvailable: true,
        expressDelivery: true,
        returnEligible: true,
        replacementEligible: true,
        metaTitle: "Cold Pressed Coconut Oil 1L | BlueAgle Natural Oils",
        metaDescription: "Shop BlueAgle Cold Pressed Coconut Oil 1L bottle. Pure unrefined oil for kitchen and home wellness.",
        metaKeywords: "cold pressed coconut oil 1l, coconut oil 1 litre, natural copra oil, blueagle",
        customAttributes: { extractionMethod: "Cold Pressed", packagingType: "Food Grade Bottle", origin: "India" },
        highlights: [
            { icon: "FaLeaf", title: "Unrefined Quality", description: "No synthetic deodorizing or chemical refining.", sortOrder: 1 }
        ],
        specifications: [
            { groupName: "Details", specKey: "Volume", specValue: "1 Litre", sortOrder: 1 }
        ],
        badges: []
    },

    // Subcategory 9: Sesame Oil
    {
        name: "Cold Pressed Sesame Oil - 500ml",
        slug: "cold-pressed-sesame-oil-500ml",
        shortName: "Cold Pressed Sesame 500ml",
        sku: "BAG-CPO-SEO-500M",
        barcode: "8901234500901",
        subCategoryId: 9,
        brand: "BlueAgle",
        shortDescription: "Aromatic cold pressed sesame (til) oil pressed from selected sesame seeds.",
        description: "BlueAgle Cold Pressed Sesame Oil is extracted from high grade natural sesame seeds without high heat. Celebrated for its rich nutty aroma and deep golden amber color, it is a staple in traditional South Indian cooking.",
        price: 250.00,
        mrp: 300.00,
        costPrice: 195.00,
        gstPercentage: 5.00,
        taxStatus: "Taxable",
        weight: "500ml",
        stock: 90,
        lowStockAlert: 10,
        minOrderQuantity: 1,
        maxOrderQuantity: 15,
        trackInventory: true,
        stockStatus: "In Stock",
        warehouseLocation: "A3-R01",
        images: [],
        videoUrl: null,
        isFeatured: true,
        isNewArrival: false,
        isBestSeller: false,
        isRecommended: true,
        isTrending: false,
        status: "Published",
        visibility: "Public",
        rating: 4.7,
        reviewCount: 64,
        viewCount: 980,
        tags: ["Sesame Oil", "Til Oil", "Cold Pressed", "Gingelly"],
        ingredients: ["100% Pure Natural Sesame Seeds"],
        benefits: ["Distinct nutty aroma for spicy gravies", "Traditional tempering oil for pickles and podis", "Extracted without chemical processing"],
        usageInstructions: ["Perfect for tempering, spicy curries, and pickling", "Keep container closed in a dark pantry", "Use within 9 months"],
        deliveryTime: "2-4 Days",
        shippingMethod: "Standard Delivery",
        codAvailable: true,
        expressDelivery: true,
        returnEligible: true,
        replacementEligible: true,
        metaTitle: "Cold Pressed Sesame Oil 500ml | BlueAgle Til Oil",
        metaDescription: "Buy BlueAgle Cold Pressed Sesame Oil 500ml. Authentic aromatic til oil for South Indian tempering.",
        metaKeywords: "cold pressed sesame oil 500ml, til oil, gingelly oil, blueagle sesame oil",
        customAttributes: { extractionMethod: "Cold Expeller Pressed", packagingType: "Food Grade Bottle", origin: "India" },
        highlights: [
            { icon: "FaLeaf", title: "Rich Aroma", description: "Characteristic nutty scent from natural sesame seeds.", sortOrder: 1 }
        ],
        specifications: [
            { groupName: "Product Info", specKey: "Volume", specValue: "500 ml", sortOrder: 1 }
        ],
        badges: [{ badgeText: "Aromatic", color: "#d97706", icon: "FaSparkles", sortOrder: 1 }]
    },
    {
        name: "Cold Pressed Sesame Oil - 1L",
        slug: "cold-pressed-sesame-oil-1l",
        shortName: "Cold Pressed Sesame 1L",
        sku: "BAG-CPO-SEO-1L",
        barcode: "8901234500902",
        subCategoryId: 9,
        brand: "BlueAgle",
        shortDescription: "1-liter bottle of unrefined cold pressed sesame til cooking oil.",
        description: "BlueAgle Cold Pressed Sesame Oil 1L offers authentic flavor and essential natural sesame compounds. Extracted slowly to maintain low process temperatures, ensuring a full-bodied culinary experience.",
        price: 480.00,
        mrp: 576.00,
        costPrice: 375.00,
        gstPercentage: 5.00,
        taxStatus: "Taxable",
        weight: "1L",
        stock: 130,
        lowStockAlert: 12,
        minOrderQuantity: 1,
        maxOrderQuantity: 20,
        trackInventory: true,
        stockStatus: "In Stock",
        warehouseLocation: "A3-R02",
        images: [],
        videoUrl: null,
        isFeatured: false,
        isNewArrival: false,
        isBestSeller: true,
        isRecommended: true,
        isTrending: true,
        status: "Published",
        visibility: "Public",
        rating: 4.8,
        reviewCount: 88,
        viewCount: 1650,
        tags: ["Sesame Oil", "Til Oil", "1 Litre", "Cold Pressed"],
        ingredients: ["100% Cleaned Sesame Seeds"],
        benefits: ["Ideal for traditional South Indian cuisine", "Adds rich taste to chutneys and spicy gravies", "Free from synthetic solvent residues"],
        usageInstructions: ["Ideal for daily cooking, gravy preparation, and pickles", "Store away from heat sources", "Close cap after use"],
        deliveryTime: "2-4 Days",
        shippingMethod: "Standard Delivery",
        codAvailable: true,
        expressDelivery: true,
        returnEligible: true,
        replacementEligible: true,
        metaTitle: "Cold Pressed Sesame Oil 1L | BlueAgle Natural Oils",
        metaDescription: "Order BlueAgle Cold Pressed Sesame Oil 1L. Pure unrefined til oil for healthy cooking.",
        metaKeywords: "cold pressed sesame oil 1l, til oil 1 litre, gingelly oil, blueagle",
        customAttributes: { extractionMethod: "Cold Expeller Pressed", packagingType: "Food Grade Bottle", origin: "India" },
        highlights: [
            { icon: "FaCheck", title: "Natural Color", description: "Deep golden color from natural seed coats.", sortOrder: 1 }
        ],
        specifications: [
            { groupName: "Product Info", specKey: "Volume", specValue: "1 Litre", sortOrder: 1 }
        ],
        badges: []
    },

    // Subcategory 10: Sunflower Oil
    {
        name: "Cold Pressed Sunflower Oil - 1L",
        slug: "cold-pressed-sunflower-oil-1l",
        shortName: "Cold Pressed Sunflower 1L",
        sku: "BAG-CPO-SFO-1L",
        barcode: "8901234501001",
        subCategoryId: 10,
        brand: "BlueAgle",
        shortDescription: "Light & clean cold pressed sunflower oil for everyday light cooking.",
        description: "BlueAgle Cold Pressed Sunflower Oil 1L is mechanically pressed from premium sunflower seeds. Light in viscosity and subtle in flavor, it allows the true taste of your ingredients to shine through.",
        price: 310.00,
        mrp: 370.00,
        costPrice: 245.00,
        gstPercentage: 5.00,
        taxStatus: "Taxable",
        weight: "1L",
        stock: 110,
        lowStockAlert: 10,
        minOrderQuantity: 1,
        maxOrderQuantity: 20,
        trackInventory: true,
        stockStatus: "In Stock",
        warehouseLocation: "A4-R01",
        images: [],
        videoUrl: null,
        isFeatured: false,
        isNewArrival: true,
        isBestSeller: false,
        isRecommended: false,
        isTrending: false,
        status: "Published",
        visibility: "Public",
        rating: 4.6,
        reviewCount: 42,
        viewCount: 740,
        tags: ["Sunflower Oil", "Cold Pressed", "Light Oil", "1 Litre"],
        ingredients: ["100% Raw Sunflower Seeds"],
        benefits: ["Light texture and neutral taste profile", "Suitable for baking, stir-frying, and light sautéing", "Unrefined cold pressed extraction"],
        usageInstructions: ["Use for light stir frying, continental dishes, and baking", "Store in a cool dry area", "Reseal tightly after use"],
        deliveryTime: "2-4 Days",
        shippingMethod: "Standard Delivery",
        codAvailable: true,
        expressDelivery: true,
        returnEligible: true,
        replacementEligible: true,
        metaTitle: "Cold Pressed Sunflower Oil 1L | BlueAgle Light Cooking Oil",
        metaDescription: "Buy BlueAgle Cold Pressed Sunflower Oil 1L online. Light unrefined oil for versatile everyday cooking.",
        metaKeywords: "cold pressed sunflower oil 1l, light cooking oil, unrefined sunflower oil, blueagle",
        customAttributes: { extractionMethod: "Cold Pressed", packagingType: "Food Grade Bottle", origin: "India" },
        highlights: [
            { icon: "FaFeather", title: "Light Flavor Profile", description: "Neutral taste that does not overpower subtle food flavors.", sortOrder: 1 }
        ],
        specifications: [
            { groupName: "Product Info", specKey: "Volume", specValue: "1 Litre", sortOrder: 1 }
        ],
        badges: [{ badgeText: "Light & Neutral", color: "#eab308", icon: "FaSun", sortOrder: 1 }]
    },
    {
        name: "Cold Pressed Sunflower Oil - 5L Can",
        slug: "cold-pressed-sunflower-oil-5l",
        shortName: "Cold Pressed Sunflower 5L",
        sku: "BAG-CPO-SFO-5L",
        barcode: "8901234501002",
        subCategoryId: 10,
        brand: "BlueAgle",
        shortDescription: "5-liter bulk can of light unrefined cold pressed sunflower cooking oil.",
        description: "Economical 5L family pack of BlueAgle Cold Pressed Sunflower Oil. Offers clean, light cooking performance for modern daily recipes.",
        price: 1480.00,
        mrp: 1750.00,
        costPrice: 1180.00,
        gstPercentage: 5.00,
        taxStatus: "Taxable",
        weight: "5L",
        stock: 35,
        lowStockAlert: 5,
        minOrderQuantity: 1,
        maxOrderQuantity: 5,
        trackInventory: true,
        stockStatus: "In Stock",
        warehouseLocation: "A4-R02",
        images: [],
        videoUrl: null,
        isFeatured: false,
        isNewArrival: false,
        isBestSeller: false,
        isRecommended: false,
        isTrending: false,
        status: "Published",
        visibility: "Public",
        rating: 4.5,
        reviewCount: 22,
        viewCount: 380,
        tags: ["Sunflower Oil", "5L Can", "Cold Pressed", "Bulk Pack"],
        ingredients: ["100% Sunflower Seeds"],
        benefits: ["Great value for regular kitchen needs", "Light and easy to digest", "Chemical-free mechanical extraction"],
        usageInstructions: ["Refill kitchen oil dispensers as required", "Keep closed in a cool dark pantry", "Avoid exposure to sunlight"],
        deliveryTime: "3-5 Days",
        shippingMethod: "Heavy Cargo Delivery",
        codAvailable: true,
        expressDelivery: false,
        returnEligible: true,
        replacementEligible: true,
        metaTitle: "Cold Pressed Sunflower Oil 5L Can | BlueAgle Bulk Packs",
        metaDescription: "Order BlueAgle Cold Pressed Sunflower Oil 5L jar. Economy size light cooking oil for family kitchens.",
        metaKeywords: "cold pressed sunflower oil 5l, bulk sunflower oil, blueagle oil",
        customAttributes: { extractionMethod: "Cold Pressed", packagingType: "HDPE Handle Can", origin: "India" },
        highlights: [
            { icon: "FaBoxes", title: "Bulk Economy", description: "Convenient 5-liter size for continuous monthly supply.", sortOrder: 1 }
        ],
        specifications: [
            { groupName: "Product Info", specKey: "Volume", specValue: "5 Litres", sortOrder: 1 }
        ],
        badges: []
    },

    // Subcategory 11: Mustard Oil
    {
        name: "Cold Pressed Mustard Oil - 1L",
        slug: "cold-pressed-mustard-oil-1l",
        shortName: "Cold Pressed Mustard 1L",
        sku: "BAG-CPO-MUO-1L",
        barcode: "8901234501101",
        subCategoryId: 11,
        brand: "BlueAgle",
        shortDescription: "Pungent & robust cold pressed kachi ghani mustard oil.",
        description: "BlueAgle Cold Pressed Mustard Oil 1L is extracted from sharp black mustard seeds using traditional cold pressing techniques. Retains authentic natural pungency (jhal) and golden clarity, essential for North Indian and Bengali cuisines.",
        price: 290.00,
        mrp: 348.00,
        costPrice: 225.00,
        gstPercentage: 5.00,
        taxStatus: "Taxable",
        weight: "1L",
        stock: 95,
        lowStockAlert: 10,
        minOrderQuantity: 1,
        maxOrderQuantity: 20,
        trackInventory: true,
        stockStatus: "In Stock",
        warehouseLocation: "A5-R01",
        images: [],
        videoUrl: null,
        isFeatured: true,
        isNewArrival: false,
        isBestSeller: false,
        isRecommended: true,
        isTrending: false,
        status: "Published",
        visibility: "Public",
        rating: 4.8,
        reviewCount: 78,
        viewCount: 1250,
        tags: ["Mustard Oil", "Kachi Ghani", "Cold Pressed", "1 Litre", "Pungent"],
        ingredients: ["100% Black Mustard Seeds"],
        benefits: ["Authentic sharp pungency and rich aroma", "Essential for North Indian & East Indian traditional dishes", "Preserves natural allylisothiocyanate compound"],
        usageInstructions: ["Heat until light smoke point before sautéing vegetables or fish", "Excellent for pickling", "Keep bottle capped after use"],
        deliveryTime: "2-4 Days",
        shippingMethod: "Standard Delivery",
        codAvailable: true,
        expressDelivery: true,
        returnEligible: true,
        replacementEligible: true,
        metaTitle: "Cold Pressed Mustard Oil 1L | BlueAgle Kachi Ghani Oil",
        metaDescription: "Shop BlueAgle Cold Pressed Mustard Oil 1L. Authentic unrefined Kachi Ghani mustard oil with rich natural aroma.",
        metaKeywords: "cold pressed mustard oil 1l, kachi ghani mustard oil, sarson ka tel, blueagle mustard oil",
        customAttributes: { extractionMethod: "Cold Pressed Kachi Ghani", packagingType: "Food Grade Bottle", origin: "India" },
        highlights: [
            { icon: "FaPepperHot", title: "Authentic Pungency", description: "Sharp natural aroma preferred for traditional Indian cooking.", sortOrder: 1 }
        ],
        specifications: [
            { groupName: "Product Info", specKey: "Pungency Grade", specValue: "High (Authentic Kachi Ghani)", sortOrder: 1 },
            { groupName: "Volume", specKey: "Net Content", specValue: "1 Litre", sortOrder: 2 }
        ],
        badges: [{ badgeText: "Kachi Ghani", color: "#ca8a04", icon: "FaCheck", sortOrder: 1 }]
    },

    // Subcategory 12: Castor Oil
    {
        name: "Cold Pressed Castor Oil - 500ml",
        slug: "cold-pressed-castor-oil-500ml",
        shortName: "Cold Pressed Castor 500ml",
        sku: "BAG-CPO-CAO-500M",
        barcode: "8901234501201",
        subCategoryId: 12,
        brand: "BlueAgle",
        shortDescription: "Pure thick cold pressed castor oil for traditional wellness & care.",
        description: "BlueAgle Cold Pressed Castor Oil 500ml is extracted from high-quality castor beans without chemical extraction. Known for its thick viscosity, it is a well-known traditional staple for topical application and household care.",
        price: 280.00,
        mrp: 340.00,
        costPrice: 210.00,
        gstPercentage: 5.00,
        taxStatus: "Taxable",
        weight: "500ml",
        stock: 60,
        lowStockAlert: 8,
        minOrderQuantity: 1,
        maxOrderQuantity: 10,
        trackInventory: true,
        stockStatus: "In Stock",
        warehouseLocation: "A5-R02",
        images: [],
        videoUrl: null,
        isFeatured: false,
        isNewArrival: true,
        isBestSeller: false,
        isRecommended: false,
        isTrending: false,
        status: "Published",
        visibility: "Public",
        rating: 4.7,
        reviewCount: 35,
        viewCount: 520,
        tags: ["Castor Oil", "Cold Pressed", "Unrefined", "Wellness Care"],
        ingredients: ["100% Castor Bean Seeds"],
        benefits: ["Thick viscous natural texture", "Hexane-free cold extraction", "Traditional multi-purpose oil"],
        usageInstructions: ["Apply topically as desired", "Store in a cool place away from sun", "For external and traditional home use"],
        deliveryTime: "2-4 Days",
        shippingMethod: "Standard Delivery",
        codAvailable: true,
        expressDelivery: true,
        returnEligible: true,
        replacementEligible: true,
        metaTitle: "Cold Pressed Castor Oil 500ml | BlueAgle Natural Care",
        metaDescription: "Buy pure BlueAgle Cold Pressed Castor Oil 500ml. Hexane-free thick unrefined castor oil.",
        metaKeywords: "cold pressed castor oil 500ml, arandi ka tel, hexane free castor oil, blueagle",
        customAttributes: { extractionMethod: "Cold Pressed", packagingType: "Amber Bottle", origin: "India" },
        highlights: [
            { icon: "FaLeaf", title: "Hexane-Free", description: "Extracted without harmful chemical solvents.", sortOrder: 1 }
        ],
        specifications: [
            { groupName: "General", specKey: "Viscosity", specValue: "High / Thick", sortOrder: 1 }
        ],
        badges: []
    },

    // Subcategory 13: Almond Oil
    {
        name: "Cold Pressed Almond Oil - 250ml",
        slug: "cold-pressed-almond-oil-250ml",
        shortName: "Cold Pressed Almond 250ml",
        sku: "BAG-CPO-ALO-250M",
        barcode: "8901234501301",
        subCategoryId: 13,
        brand: "BlueAgle",
        shortDescription: "Premium cold pressed sweet almond oil pressed from sweet almond kernels.",
        description: "BlueAgle Cold Pressed Almond Oil 250ml is a high-grade oil extracted from sweet almonds. Processed at low temperatures, it preserves delicate natural aromas and light golden clarity.",
        price: 450.00,
        mrp: 550.00,
        costPrice: 350.00,
        gstPercentage: 5.00,
        taxStatus: "Taxable",
        weight: "250ml",
        stock: 50,
        lowStockAlert: 5,
        minOrderQuantity: 1,
        maxOrderQuantity: 5,
        trackInventory: true,
        stockStatus: "In Stock",
        warehouseLocation: "A6-R01",
        images: [],
        videoUrl: null,
        isFeatured: true,
        isNewArrival: true,
        isBestSeller: false,
        isRecommended: true,
        isTrending: true,
        status: "Published",
        visibility: "Public",
        rating: 4.9,
        reviewCount: 52,
        viewCount: 1100,
        tags: ["Almond Oil", "Sweet Almond", "Cold Pressed", "Premium Oil"],
        ingredients: ["100% Sweet Almond Kernels"],
        benefits: ["Light non-greasy texture", "Pleasant mild almond scent", "Cold pressed purity without synthetic additives"],
        usageInstructions: ["Use as desired for culinary garnish or topical application", "Store in a cool dry cabinet", "Keep cap sealed"],
        deliveryTime: "2-4 Days",
        shippingMethod: "Standard Delivery",
        codAvailable: true,
        expressDelivery: true,
        returnEligible: true,
        replacementEligible: true,
        metaTitle: "Cold Pressed Almond Oil 250ml | BlueAgle Premium Oils",
        metaDescription: "Order BlueAgle Cold Pressed Sweet Almond Oil 250ml. Pure unrefined almond oil crafted for quality.",
        metaKeywords: "cold pressed almond oil 250ml, sweet almond oil, badam tel, blueagle almond oil",
        customAttributes: { extractionMethod: "Cold Pressed", packagingType: "Glass Bottle", origin: "India" },
        highlights: [
            { icon: "FaGem", title: "Sweet Almond Kernels", description: "Extracted exclusively from edible sweet almond nuts.", sortOrder: 1 }
        ],
        specifications: [
            { groupName: "Info", specKey: "Volume", specValue: "250 ml", sortOrder: 1 }
        ],
        badges: [{ badgeText: "Premium Grade", color: "#9333ea", icon: "FaCrown", sortOrder: 1 }]
    },
    {
        name: "Cold Pressed Almond Oil - 500ml",
        slug: "cold-pressed-almond-oil-500ml",
        shortName: "Cold Pressed Almond 500ml",
        sku: "BAG-CPO-ALO-500M",
        barcode: "8901234501302",
        subCategoryId: 13,
        brand: "BlueAgle",
        shortDescription: "500ml glass bottle of pure cold pressed sweet almond oil.",
        description: "Double quantity 500ml bottle of BlueAgle Cold Pressed Almond Oil. Extracted with precision to deliver unmatched almond aroma and purity.",
        price: 850.00,
        mrp: 1020.00,
        costPrice: 670.00,
        gstPercentage: 5.00,
        taxStatus: "Taxable",
        weight: "500ml",
        stock: 30,
        lowStockAlert: 5,
        minOrderQuantity: 1,
        maxOrderQuantity: 5,
        trackInventory: true,
        stockStatus: "In Stock",
        warehouseLocation: "A6-R02",
        images: [],
        videoUrl: null,
        isFeatured: false,
        isNewArrival: false,
        isBestSeller: false,
        isRecommended: false,
        isTrending: false,
        status: "Published",
        visibility: "Public",
        rating: 4.8,
        reviewCount: 29,
        viewCount: 610,
        tags: ["Almond Oil", "Sweet Almond", "500ml", "Cold Pressed"],
        ingredients: ["100% Pure Sweet Almonds"],
        benefits: ["Excellent value 500ml bottle", "Natural almond richness", "Zero mineral oil additives"],
        usageInstructions: ["Store in a cool dark place", "Keep bottle tightly closed"],
        deliveryTime: "2-4 Days",
        shippingMethod: "Standard Delivery",
        codAvailable: true,
        expressDelivery: true,
        returnEligible: true,
        replacementEligible: true,
        metaTitle: "Cold Pressed Almond Oil 500ml | BlueAgle Oils",
        metaDescription: "Buy BlueAgle Cold Pressed Almond Oil 500ml bottle online. Premium unrefined sweet almond oil.",
        metaKeywords: "cold pressed almond oil 500ml, badam oil, sweet almond oil, blueagle",
        customAttributes: { extractionMethod: "Cold Pressed", packagingType: "Glass Bottle", origin: "India" },
        highlights: [
            { icon: "FaCheck", title: "Glass Bottle Pack", description: "Preserves fresh aroma and prevents plastic interaction.", sortOrder: 1 }
        ],
        specifications: [
            { groupName: "Packaging", specKey: "Bottle Type", specValue: "UV Protection Glass Bottle", sortOrder: 1 }
        ],
        badges: []
    },

    // ─── CATEGORY 8: TRADITIONAL OILS ───────────────────────────────────────────
    // Subcategory 14: Wood Pressed Groundnut Oil
    {
        name: "Wood Pressed Groundnut Oil - 1L",
        slug: "wood-pressed-groundnut-oil-1l",
        shortName: "Wood Pressed Groundnut 1L",
        sku: "BAG-TRO-WPG-1L",
        barcode: "8901234501401",
        subCategoryId: 14,
        brand: "BlueAgle",
        shortDescription: "Traditional wood pressed (marachekku) groundnut oil with authentic aroma.",
        description: "BlueAgle Wood Pressed Groundnut Oil 1L is extracted using traditional wooden pestle chakkis (Mara Chekku). Slow rotational crushing generates minimal heat, retaining rich earthy peanut flavor and ancestral culinary heritage.",
        price: 380.00,
        mrp: 450.00,
        costPrice: 295.00,
        gstPercentage: 5.00,
        taxStatus: "Taxable",
        weight: "1L",
        stock: 160,
        lowStockAlert: 15,
        minOrderQuantity: 1,
        maxOrderQuantity: 20,
        trackInventory: true,
        stockStatus: "In Stock",
        warehouseLocation: "B1-R01",
        images: [],
        videoUrl: null,
        isFeatured: true,
        isNewArrival: false,
        isBestSeller: true,
        isRecommended: true,
        isTrending: true,
        status: "Published",
        visibility: "Public",
        rating: 4.9,
        reviewCount: 155,
        viewCount: 3100,
        tags: ["Wood Pressed", "Marachekku", "Groundnut Oil", "Traditional Oil"],
        ingredients: ["100% Sun-Dried Peanuts"],
        benefits: ["Extracted using wooden pestle (Mara Chekku)", "Authentic heritage taste and thick texture", "High smoke point for traditional Indian recipes"],
        usageInstructions: ["Ideal for frying, tiffins, and everyday cooking", "Store in a cool, dry place", "Close cap after usage"],
        deliveryTime: "2-4 Days",
        shippingMethod: "Standard Delivery",
        codAvailable: true,
        expressDelivery: true,
        returnEligible: true,
        replacementEligible: true,
        metaTitle: "Wood Pressed Groundnut Oil 1L | BlueAgle Marachekku Oil",
        metaDescription: "Buy BlueAgle Wood Pressed (Marachekku) Groundnut Oil 1L. Authentic wooden pestle crushed unrefined peanut oil.",
        metaKeywords: "wood pressed groundnut oil 1l, marachekku groundnut oil, traditional peanut oil, blueagle",
        customAttributes: { extractionMethod: "Wooden Chekku (Marachekku)", packagingType: "Food Grade PET Bottle", origin: "India" },
        highlights: [
            { icon: "FaTree", title: "Wooden Chekku (Marachekku)", description: "Slow pestle rotation prevents heat buildup and protects natural nutrients.", sortOrder: 1 },
            { icon: "FaUtensils", title: "Heritage Flavor", description: "Delivers traditional kitchen aroma like home-milled oil.", sortOrder: 2 }
        ],
        specifications: [
            { groupName: "Extraction", specKey: "Pestle Material", specValue: "Vagai (Black Siris) Wood", sortOrder: 1 },
            { groupName: "Volume", specKey: "Net Content", specValue: "1 Litre", sortOrder: 2 }
        ],
        badges: [{ badgeText: "Mara Chekku", color: "#15803d", icon: "FaTree", sortOrder: 1 }]
    },
    {
        name: "Wood Pressed Groundnut Oil - 5L Can",
        slug: "wood-pressed-groundnut-oil-5l",
        shortName: "Wood Pressed Groundnut 5L",
        sku: "BAG-TRO-WPG-5L",
        barcode: "8901234501402",
        subCategoryId: 14,
        brand: "BlueAgle",
        shortDescription: "5-liter bulk economy can of traditional wood pressed groundnut oil.",
        description: "Family bulk pack of BlueAgle Wood Pressed Groundnut Oil 5L. Prepared via traditional wooden chekku milling for wholesome monthly cooking.",
        price: 1850.00,
        mrp: 2200.00,
        costPrice: 1480.00,
        gstPercentage: 5.00,
        taxStatus: "Taxable",
        weight: "5L",
        stock: 50,
        lowStockAlert: 5,
        minOrderQuantity: 1,
        maxOrderQuantity: 5,
        trackInventory: true,
        stockStatus: "In Stock",
        warehouseLocation: "B1-R02",
        images: [],
        videoUrl: null,
        isFeatured: false,
        isNewArrival: false,
        isBestSeller: true,
        isRecommended: true,
        isTrending: false,
        status: "Published",
        visibility: "Public",
        rating: 4.8,
        reviewCount: 48,
        viewCount: 890,
        tags: ["Wood Pressed", "Marachekku", "5L Can", "Bulk Pack"],
        ingredients: ["100% Peanuts"],
        benefits: ["Economical family size", "Authentic wooden chekku milling", "Unrefined and chemical free"],
        usageInstructions: ["Dispense into smaller kitchen bottles", "Store away from heat and moisture"],
        deliveryTime: "3-5 Days",
        shippingMethod: "Heavy Cargo Delivery",
        codAvailable: true,
        expressDelivery: false,
        returnEligible: true,
        replacementEligible: true,
        metaTitle: "Wood Pressed Groundnut Oil 5L Can | BlueAgle",
        metaDescription: "Order BlueAgle Wood Pressed Groundnut Oil 5L jar. Traditional Marachekku peanut oil for bulk home kitchen use.",
        metaKeywords: "wood pressed groundnut oil 5l, marachekku oil 5 litres, bulk cooking oil, blueagle",
        customAttributes: { extractionMethod: "Wooden Chekku (Marachekku)", packagingType: "HDPE Handle Can", origin: "India" },
        highlights: [
            { icon: "FaBoxes", title: "Bulk Savings", description: "Superior savings for traditional cooking requirements.", sortOrder: 1 }
        ],
        specifications: [
            { groupName: "Volume", specKey: "Net Content", specValue: "5 Litres", sortOrder: 1 }
        ],
        badges: []
    },

    // Subcategory 15: Wood Pressed Sesame Oil
    {
        name: "Wood Pressed Sesame Oil - 1L",
        slug: "wood-pressed-sesame-oil-1l",
        shortName: "Wood Pressed Sesame 1L",
        sku: "BAG-TRO-WPS-1L",
        barcode: "8901234501501",
        subCategoryId: 15,
        brand: "BlueAgle",
        shortDescription: "Premium marachekku wood pressed sesame (gingelly) oil with palm jaggery.",
        description: "BlueAgle Wood Pressed Sesame Oil 1L is crafted using traditional wooden chekkus with a hint of natural palm jaggery during crushing, as per ancient South Indian oil mill traditions. Results in a smooth, deeply aromatic gingelly oil.",
        price: 510.00,
        mrp: 600.00,
        costPrice: 395.00,
        gstPercentage: 5.00,
        taxStatus: "Taxable",
        weight: "1L",
        stock: 125,
        lowStockAlert: 10,
        minOrderQuantity: 1,
        maxOrderQuantity: 20,
        trackInventory: true,
        stockStatus: "In Stock",
        warehouseLocation: "B2-R01",
        images: [],
        videoUrl: null,
        isFeatured: true,
        isNewArrival: false,
        isBestSeller: true,
        isRecommended: true,
        isTrending: true,
        status: "Published",
        visibility: "Public",
        rating: 4.9,
        reviewCount: 120,
        viewCount: 2200,
        tags: ["Wood Pressed", "Sesame Oil", "Gingelly Oil", "Marachekku", "Palm Jaggery"],
        ingredients: ["98% Natural Sesame Seeds", "2% Pure Palm Jaggery"],
        benefits: ["Crushed with traditional palm jaggery to balance bitterness", "Authentic rich golden brown color and deep aroma", "Unrefined and cold-extracted via wooden pestle"],
        usageInstructions: ["Excellent for tempering, Kara Kuzhambu, and traditional dishes", "Store in a cool dry pantry", "Keep bottle tightly closed"],
        deliveryTime: "2-4 Days",
        shippingMethod: "Standard Delivery",
        codAvailable: true,
        expressDelivery: true,
        returnEligible: true,
        replacementEligible: true,
        metaTitle: "Wood Pressed Sesame Oil 1L | BlueAgle Nalla Ennai",
        metaDescription: "Buy BlueAgle Wood Pressed (Marachekku) Sesame Oil 1L with palm jaggery. Traditional Nalla Ennai for authentic Indian cooking.",
        metaKeywords: "wood pressed sesame oil 1l, marachekku gingelly oil, nalla ennai, blueagle sesame oil",
        customAttributes: { extractionMethod: "Wooden Chekku with Palm Jaggery", packagingType: "Food Grade Bottle", origin: "India" },
        highlights: [
            { icon: "FaTree", title: "Traditional Palm Jaggery Additive", description: "Crushed using natural palm jaggery for smoother flavor.", sortOrder: 1 },
            { icon: "FaSparkles", title: "Aromatic Nalla Ennai", description: "Deep flavor profile ideal for authentic South Indian curries.", sortOrder: 2 }
        ],
        specifications: [
            { groupName: "Method", specKey: "Extraction Process", specValue: "Wooden Pestle (Marachekku)", sortOrder: 1 },
            { groupName: "Volume", specKey: "Net Content", specValue: "1 Litre", sortOrder: 2 }
        ],
        badges: [{ badgeText: "Traditional Jaggery", color: "#7c2d12", icon: "FaTree", sortOrder: 1 }]
    },
    {
        name: "Wood Pressed Sesame Oil - 5L Can",
        slug: "wood-pressed-sesame-oil-5l",
        shortName: "Wood Pressed Sesame 5L",
        sku: "BAG-TRO-WPS-5L",
        barcode: "8901234501502",
        subCategoryId: 15,
        brand: "BlueAgle",
        shortDescription: "5-liter bulk jar of marachekku wood pressed sesame gingelly oil.",
        description: "Economy 5L pack of BlueAgle Wood Pressed Sesame Oil. Provides pure traditional gingelly oil in bulk for monthly family consumption.",
        price: 2450.00,
        mrp: 2900.00,
        costPrice: 1950.00,
        gstPercentage: 5.00,
        taxStatus: "Taxable",
        weight: "5L",
        stock: 30,
        lowStockAlert: 5,
        minOrderQuantity: 1,
        maxOrderQuantity: 5,
        trackInventory: true,
        stockStatus: "In Stock",
        warehouseLocation: "B2-R02",
        images: [],
        videoUrl: null,
        isFeatured: false,
        isNewArrival: false,
        isBestSeller: false,
        isRecommended: true,
        isTrending: false,
        status: "Published",
        visibility: "Public",
        rating: 4.8,
        reviewCount: 31,
        viewCount: 540,
        tags: ["Wood Pressed", "Sesame Oil", "5L Can", "Marachekku"],
        ingredients: ["Natural Sesame Seeds", "Palm Jaggery"],
        benefits: ["Bulk savings for daily traditional cooking", "Wooden pestle extracted quality"],
        usageInstructions: ["Refill smaller dispensers as needed", "Store in a cool dry area"],
        deliveryTime: "3-5 Days",
        shippingMethod: "Heavy Cargo Delivery",
        codAvailable: true,
        expressDelivery: false,
        returnEligible: true,
        replacementEligible: true,
        metaTitle: "Wood Pressed Sesame Oil 5L Can | BlueAgle",
        metaDescription: "Buy BlueAgle Wood Pressed Sesame Oil 5L bulk container. Pure Marachekku Nalla Ennai.",
        metaKeywords: "wood pressed sesame oil 5l, marachekku gingelly oil 5 litres, blueagle",
        customAttributes: { extractionMethod: "Wooden Chekku", packagingType: "HDPE Handle Can", origin: "India" },
        highlights: [
            { icon: "FaBoxes", title: "Bulk Saver Pack", description: "Substantial savings for traditional households.", sortOrder: 1 }
        ],
        specifications: [
            { groupName: "Volume", specKey: "Net Content", specValue: "5 Litres", sortOrder: 1 }
        ],
        badges: []
    },

    // Subcategory 16: Wood Pressed Coconut Oil
    {
        name: "Wood Pressed Coconut Oil - 1L",
        slug: "wood-pressed-coconut-oil-1l",
        shortName: "Wood Pressed Coconut 1L",
        sku: "BAG-TRO-WPC-1L",
        barcode: "8901234501601",
        subCategoryId: 16,
        brand: "BlueAgle",
        shortDescription: "Wooden chekku crushed unrefined coconut oil made from sun-dried copra.",
        description: "BlueAgle Wood Pressed Coconut Oil 1L is extracted using traditional wooden mills from premium quality dried coconut copra. Retains natural sweet coconut flavor and unrefined coconut fats.",
        price: 440.00,
        mrp: 520.00,
        costPrice: 345.00,
        gstPercentage: 5.00,
        taxStatus: "Taxable",
        weight: "1L",
        stock: 140,
        lowStockAlert: 12,
        minOrderQuantity: 1,
        maxOrderQuantity: 20,
        trackInventory: true,
        stockStatus: "In Stock",
        warehouseLocation: "B3-R01",
        images: [],
        videoUrl: null,
        isFeatured: true,
        isNewArrival: false,
        isBestSeller: true,
        isRecommended: true,
        isTrending: false,
        status: "Published",
        visibility: "Public",
        rating: 4.9,
        reviewCount: 92,
        viewCount: 1780,
        tags: ["Wood Pressed", "Coconut Oil", "Marachekku", "1 Litre"],
        ingredients: ["100% Sun-Dried Coconut Copra"],
        benefits: ["Traditional wooden chekku milling", "Sweet coconut taste and tropical aroma", "Zero heat treatment or refining"],
        usageInstructions: ["Ideal for Kerala & Tamil Nadu dishes, curries, and roasting", "Store in a dry location", "Liquefy in warm water if solidified"],
        deliveryTime: "2-4 Days",
        shippingMethod: "Standard Delivery",
        codAvailable: true,
        expressDelivery: true,
        returnEligible: true,
        replacementEligible: true,
        metaTitle: "Wood Pressed Coconut Oil 1L | BlueAgle Marachekku Oil",
        metaDescription: "Shop BlueAgle Wood Pressed Coconut Oil 1L. Pure wooden chekku crushed unrefined coconut oil.",
        metaKeywords: "wood pressed coconut oil 1l, marachekku coconut oil, blueagle coconut oil",
        customAttributes: { extractionMethod: "Wooden Chekku (Marachekku)", packagingType: "Food Grade Bottle", origin: "India" },
        highlights: [
            { icon: "FaTree", title: "Wooden Chekku Extracted", description: "Zero heat build-up during extraction to retain raw fresh flavor.", sortOrder: 1 }
        ],
        specifications: [
            { groupName: "Info", specKey: "Volume", specValue: "1 Litre", sortOrder: 1 }
        ],
        badges: [{ badgeText: "Marachekku", color: "#0284c7", icon: "FaTree", sortOrder: 1 }]
    },

    // Subcategory 17: Traditional Gingelly Oil
    {
        name: "Traditional Gingelly Oil - 500ml",
        slug: "traditional-gingelly-oil-500ml",
        shortName: "Traditional Gingelly 500ml",
        sku: "BAG-TRO-TGO-500M",
        barcode: "8901234501701",
        subCategoryId: 17,
        brand: "BlueAgle",
        shortDescription: "Authentic South Indian traditional gingelly oil for daily cooking.",
        description: "BlueAgle Traditional Gingelly Oil 500ml is prepared following time-tested South Indian oil mill recipes. Natural sesame seeds are pressed gently to deliver rich golden hue and savory culinary depth.",
        price: 260.00,
        mrp: 310.00,
        costPrice: 200.00,
        gstPercentage: 5.00,
        taxStatus: "Taxable",
        weight: "500ml",
        stock: 85,
        lowStockAlert: 10,
        minOrderQuantity: 1,
        maxOrderQuantity: 15,
        trackInventory: true,
        stockStatus: "In Stock",
        warehouseLocation: "B4-R01",
        images: [],
        videoUrl: null,
        isFeatured: false,
        isNewArrival: false,
        isBestSeller: false,
        isRecommended: false,
        isTrending: false,
        status: "Published",
        visibility: "Public",
        rating: 4.7,
        reviewCount: 45,
        viewCount: 720,
        tags: ["Gingelly Oil", "Traditional", "Til Oil", "500ml"],
        ingredients: ["100% Sesame Seeds", "Traces of Jaggery"],
        benefits: ["Traditional South Indian recipe", "Smooth non-bitter taste profile", "Great for pickles and gravies"],
        usageInstructions: ["Use for daily tempering, gravies, and pickles", "Keep in a cool dry pantry"],
        deliveryTime: "2-4 Days",
        shippingMethod: "Standard Delivery",
        codAvailable: true,
        expressDelivery: true,
        returnEligible: true,
        replacementEligible: true,
        metaTitle: "Traditional Gingelly Oil 500ml | BlueAgle Oils",
        metaDescription: "Buy BlueAgle Traditional Gingelly Oil 500ml. Authentic South Indian til oil for daily cooking.",
        metaKeywords: "traditional gingelly oil 500ml, nalla ennai, til oil, blueagle",
        customAttributes: { extractionMethod: "Traditional Expeller", packagingType: "Food Grade Bottle", origin: "India" },
        highlights: [
            { icon: "FaUtensils", title: "South Indian Classic", description: "Specially formulated for traditional kuzhambu & pickle preparations.", sortOrder: 1 }
        ],
        specifications: [
            { groupName: "Product Info", specKey: "Volume", specValue: "500 ml", sortOrder: 1 }
        ],
        badges: []
    },
    {
        name: "Traditional Gingelly Oil - 1L",
        slug: "traditional-gingelly-oil-1l",
        shortName: "Traditional Gingelly 1L",
        sku: "BAG-TRO-TGO-1L",
        barcode: "8901234501702",
        subCategoryId: 17,
        brand: "BlueAgle",
        shortDescription: "1-liter bottle of authentic South Indian traditional gingelly oil.",
        description: "BlueAgle Traditional Gingelly Oil 1L delivers classic South Indian culinary taste with rich nutty aroma and smooth finish.",
        price: 495.00,
        mrp: 590.00,
        costPrice: 385.00,
        gstPercentage: 5.00,
        taxStatus: "Taxable",
        weight: "1L",
        stock: 115,
        lowStockAlert: 12,
        minOrderQuantity: 1,
        maxOrderQuantity: 20,
        trackInventory: true,
        stockStatus: "In Stock",
        warehouseLocation: "B4-R02",
        images: [],
        videoUrl: null,
        isFeatured: false,
        isNewArrival: false,
        isBestSeller: true,
        isRecommended: true,
        isTrending: false,
        status: "Published",
        visibility: "Public",
        rating: 4.8,
        reviewCount: 67,
        viewCount: 1350,
        tags: ["Gingelly Oil", "Traditional", "1 Litre", "Nalla Ennai"],
        ingredients: ["Sesame Seeds", "Palm Jaggery"],
        benefits: ["Traditional taste profile", "Unrefined mechanical pressing"],
        usageInstructions: ["Ideal for curries, tempering, and gravies", "Store in a cool dry area"],
        deliveryTime: "2-4 Days",
        shippingMethod: "Standard Delivery",
        codAvailable: true,
        expressDelivery: true,
        returnEligible: true,
        replacementEligible: true,
        metaTitle: "Traditional Gingelly Oil 1L | BlueAgle",
        metaDescription: "Order BlueAgle Traditional Gingelly Oil 1L bottle. Pure authentic South Indian sesame oil.",
        metaKeywords: "traditional gingelly oil 1l, nalla ennai 1 litre, blueagle",
        customAttributes: { extractionMethod: "Traditional Expeller", packagingType: "Food Grade Bottle", origin: "India" },
        highlights: [
            { icon: "FaCheck", title: "Time-Tested Quality", description: "Crafted following traditional regional milling practices.", sortOrder: 1 }
        ],
        specifications: [
            { groupName: "Product Info", specKey: "Volume", specValue: "1 Litre", sortOrder: 1 }
        ],
        badges: []
    },

    // ─── CATEGORY 9: NUTS & SEEDS ───────────────────────────────────────────────
    // Subcategory 18: Groundnuts
    {
        name: "Premium Raw Groundnuts - 250g",
        slug: "premium-raw-groundnuts-250g",
        shortName: "Raw Groundnuts 250g",
        sku: "BAG-NTS-GNT-250G",
        barcode: "8901234501801",
        subCategoryId: 18,
        brand: "BlueAgle",
        shortDescription: "Cleaned raw groundnut kernels selected for snacking and oil mill roasting.",
        description: "BlueAgle Premium Raw Groundnuts 250g are sun-dried, bold-sized peanut kernels. Cleaned and graded to ensure uniform crunch, sweetness, and high natural oil content.",
        price: 110.00,
        mrp: 130.00,
        costPrice: 85.00,
        gstPercentage: 5.00,
        taxStatus: "Taxable",
        weight: "250g",
        stock: 150,
        lowStockAlert: 15,
        minOrderQuantity: 1,
        maxOrderQuantity: 20,
        trackInventory: true,
        stockStatus: "In Stock",
        warehouseLocation: "C1-R01",
        images: [],
        videoUrl: null,
        isFeatured: false,
        isNewArrival: true,
        isBestSeller: false,
        isRecommended: false,
        isTrending: false,
        status: "Published",
        visibility: "Public",
        rating: 4.7,
        reviewCount: 38,
        viewCount: 540,
        tags: ["Groundnuts", "Peanuts", "Raw Nuts", "250g", "Snacks"],
        ingredients: ["100% Raw Groundnut Kernels"],
        benefits: ["Cleaned & graded bold kernels", "Ideal for roasting, chikkis, and chutneys", "High natural oil content"],
        usageInstructions: ["Roast or boil for healthy snacking", "Use in chutneys, sweets, and gravies", "Store in an airtight container"],
        deliveryTime: "2-4 Days",
        shippingMethod: "Standard Delivery",
        codAvailable: true,
        expressDelivery: true,
        returnEligible: true,
        replacementEligible: true,
        metaTitle: "Premium Raw Groundnuts 250g | BlueAgle Natural Seeds",
        metaDescription: "Buy BlueAgle Premium Raw Groundnuts 250g. Cleaned bold peanut kernels for snacking and cooking.",
        metaKeywords: "raw groundnuts 250g, peanuts, raw peanuts, blueagle nuts",
        customAttributes: { processing: "Naturally Cleaned & Sun Dried", packagingType: "Pouch Pack", origin: "India" },
        highlights: [
            { icon: "FaSeedling", title: "Bold Size Kernels", description: "Carefully sorted for uniform grain size and natural sweetness.", sortOrder: 1 }
        ],
        specifications: [
            { groupName: "Product Details", specKey: "Weight", specValue: "250 grams", sortOrder: 1 }
        ],
        badges: []
    },
    {
        name: "Premium Raw Groundnuts - 500g",
        slug: "premium-raw-groundnuts-500g",
        shortName: "Raw Groundnuts 500g",
        sku: "BAG-NTS-GNT-500G",
        barcode: "8901234501802",
        subCategoryId: 18,
        brand: "BlueAgle",
        shortDescription: "500g pack of cleaned bold raw groundnut peanuts.",
        description: "BlueAgle Premium Raw Groundnuts 500g provides high quality raw peanuts ideal for daily kitchen preparation, roasting, and traditional sweets.",
        price: 210.00,
        mrp: 250.00,
        costPrice: 160.00,
        gstPercentage: 5.00,
        taxStatus: "Taxable",
        weight: "500g",
        stock: 200,
        lowStockAlert: 20,
        minOrderQuantity: 1,
        maxOrderQuantity: 20,
        trackInventory: true,
        stockStatus: "In Stock",
        warehouseLocation: "C1-R02",
        images: [],
        videoUrl: null,
        isFeatured: true,
        isNewArrival: false,
        isBestSeller: true,
        isRecommended: true,
        isTrending: false,
        status: "Published",
        visibility: "Public",
        rating: 4.8,
        reviewCount: 84,
        viewCount: 1490,
        tags: ["Groundnuts", "Peanuts", "Raw Nuts", "500g"],
        ingredients: ["100% Raw Groundnut Seeds"],
        benefits: ["Rich in protein and natural fats", "Crisp texture when roasted", "Hygienically packed"],
        usageInstructions: ["Roast, fry, or add to poha and chutneys", "Transfer to airtight container after opening"],
        deliveryTime: "2-4 Days",
        shippingMethod: "Standard Delivery",
        codAvailable: true,
        expressDelivery: true,
        returnEligible: true,
        replacementEligible: true,
        metaTitle: "Premium Raw Groundnuts 500g | BlueAgle",
        metaDescription: "Shop BlueAgle Premium Raw Groundnuts 500g. Fresh cleaned peanuts for daily cooking.",
        metaKeywords: "raw groundnuts 500g, peanuts 500g, blueagle groundnuts",
        customAttributes: { processing: "Naturally Cleaned & Sun Dried", packagingType: "Sealed Pouch", origin: "India" },
        highlights: [
            { icon: "FaCheck", title: "Hygienic Sealed Pack", description: "Sealed to retain natural crunch and freshness.", sortOrder: 1 }
        ],
        specifications: [
            { groupName: "Product Details", specKey: "Weight", specValue: "500 grams", sortOrder: 1 }
        ],
        badges: [{ badgeText: "Popular", color: "#16a34a", icon: "FaCheck", sortOrder: 1 }]
    },
    {
        name: "Premium Raw Groundnuts - 1kg",
        slug: "premium-raw-groundnuts-1kg",
        shortName: "Raw Groundnuts 1kg",
        sku: "BAG-NTS-GNT-1KG",
        barcode: "8901234501803",
        subCategoryId: 18,
        brand: "BlueAgle",
        shortDescription: "1kg value pack of clean raw groundnut peanuts.",
        description: "1kg bulk economy bag of BlueAgle Premium Raw Groundnuts. Ideal for home roasting and culinary recipes.",
        price: 390.00,
        mrp: 470.00,
        costPrice: 300.00,
        gstPercentage: 5.00,
        taxStatus: "Taxable",
        weight: "1kg",
        stock: 130,
        lowStockAlert: 15,
        minOrderQuantity: 1,
        maxOrderQuantity: 10,
        trackInventory: true,
        stockStatus: "In Stock",
        warehouseLocation: "C1-R03",
        images: [],
        videoUrl: null,
        isFeatured: false,
        isNewArrival: false,
        isBestSeller: false,
        isRecommended: false,
        isTrending: false,
        status: "Published",
        visibility: "Public",
        rating: 4.7,
        reviewCount: 56,
        viewCount: 920,
        tags: ["Groundnuts", "Peanuts", "1kg", "Raw Nuts"],
        ingredients: ["100% Raw Groundnut Seeds"],
        benefits: ["Bulk kitchen savings", "Bold seed quality"],
        usageInstructions: ["Keep in airtight jar", "Roast or cook as per recipe"],
        deliveryTime: "2-4 Days",
        shippingMethod: "Standard Delivery",
        codAvailable: true,
        expressDelivery: true,
        returnEligible: true,
        replacementEligible: true,
        metaTitle: "Premium Raw Groundnuts 1kg | BlueAgle",
        metaDescription: "Order BlueAgle Raw Groundnuts 1kg pack. Cleaned raw peanuts for kitchen use.",
        metaKeywords: "raw groundnuts 1kg, peanuts 1kg, blueagle",
        customAttributes: { processing: "Naturally Cleaned", packagingType: "Bulk Pouch", origin: "India" },
        highlights: [
            { icon: "FaTag", title: "Value Pack", description: "Best price per kg for household pantry stocking.", sortOrder: 1 }
        ],
        specifications: [
            { groupName: "Product Details", specKey: "Weight", specValue: "1000 grams (1kg)", sortOrder: 1 }
        ],
        badges: []
    },

    // Subcategory 19: Sesame Seeds
    {
        name: "Natural White Sesame Seeds - 250g",
        slug: "natural-white-sesame-seeds-250g",
        shortName: "Sesame Seeds 250g",
        sku: "BAG-NTS-SES-250G",
        barcode: "8901234501901",
        subCategoryId: 19,
        brand: "BlueAgle",
        shortDescription: "Cleaned natural white sesame seeds (til) for baking and cooking.",
        description: "BlueAgle Natural White Sesame Seeds 250g are thoroughly cleaned til seeds with rich nutty aroma. Perfect for garnishing, bakery, and traditional Indian sweets like til laddoos.",
        price: 130.00,
        mrp: 155.00,
        costPrice: 95.00,
        gstPercentage: 5.00,
        taxStatus: "Taxable",
        weight: "250g",
        stock: 120,
        lowStockAlert: 10,
        minOrderQuantity: 1,
        maxOrderQuantity: 20,
        trackInventory: true,
        stockStatus: "In Stock",
        warehouseLocation: "C2-R01",
        images: [],
        videoUrl: null,
        isFeatured: false,
        isNewArrival: true,
        isBestSeller: false,
        isRecommended: true,
        isTrending: false,
        status: "Published",
        visibility: "Public",
        rating: 4.8,
        reviewCount: 42,
        viewCount: 680,
        tags: ["Sesame Seeds", "Til", "White Sesame", "250g"],
        ingredients: ["100% Natural White Sesame Seeds"],
        benefits: ["Thoroughly machine cleaned & destoned", "Rich nutty flavor for baking and garnishing", "Natural oil seed goodness"],
        usageInstructions: ["Toast lightly for salads, breads, and sweets", "Store in a dry airtight jar"],
        deliveryTime: "2-4 Days",
        shippingMethod: "Standard Delivery",
        codAvailable: true,
        expressDelivery: true,
        returnEligible: true,
        replacementEligible: true,
        metaTitle: "Natural White Sesame Seeds 250g | BlueAgle Seeds",
        metaDescription: "Buy BlueAgle Natural White Sesame Seeds 250g. Cleaned til seeds for cooking, garnishing & sweets.",
        metaKeywords: "white sesame seeds 250g, til seeds, safed til, blueagle seeds",
        customAttributes: { processing: "Machine Cleaned & Destoned", packagingType: "Pouch Pack", origin: "India" },
        highlights: [
            { icon: "FaCheck", title: "Machine Cleaned", description: "Free from stones, dust, and impurities.", sortOrder: 1 }
        ],
        specifications: [
            { groupName: "Details", specKey: "Weight", specValue: "250 grams", sortOrder: 1 }
        ],
        badges: []
    },
    {
        name: "Natural White Sesame Seeds - 500g",
        slug: "natural-white-sesame-seeds-500g",
        shortName: "Sesame Seeds 500g",
        sku: "BAG-NTS-SES-500G",
        barcode: "8901234501902",
        subCategoryId: 19,
        brand: "BlueAgle",
        shortDescription: "500g pack of cleaned natural white sesame til seeds.",
        description: "BlueAgle Natural White Sesame Seeds 500g provides high quality cleaned til seeds for family culinary preparation and sweets.",
        price: 240.00,
        mrp: 290.00,
        costPrice: 180.00,
        gstPercentage: 5.00,
        taxStatus: "Taxable",
        weight: "500g",
        stock: 140,
        lowStockAlert: 15,
        minOrderQuantity: 1,
        maxOrderQuantity: 20,
        trackInventory: true,
        stockStatus: "In Stock",
        warehouseLocation: "C2-R02",
        images: [],
        videoUrl: null,
        isFeatured: false,
        isNewArrival: false,
        isBestSeller: true,
        isRecommended: false,
        isTrending: false,
        status: "Published",
        visibility: "Public",
        rating: 4.8,
        reviewCount: 61,
        viewCount: 1120,
        tags: ["Sesame Seeds", "Til", "500g"],
        ingredients: ["100% White Sesame Seeds"],
        benefits: ["Cleaned & ready to use", "Aromatic natural flavor"],
        usageInstructions: ["Store in an airtight container", "Use in laddoos, chikkis, and garnishing"],
        deliveryTime: "2-4 Days",
        shippingMethod: "Standard Delivery",
        codAvailable: true,
        expressDelivery: true,
        returnEligible: true,
        replacementEligible: true,
        metaTitle: "Natural White Sesame Seeds 500g | BlueAgle",
        metaDescription: "Order BlueAgle White Sesame Seeds 500g pack. Cleaned natural til seeds.",
        metaKeywords: "sesame seeds 500g, white til 500g, blueagle",
        customAttributes: { processing: "Machine Cleaned", packagingType: "Pouch Pack", origin: "India" },
        highlights: [
            { icon: "FaSeedling", title: "Natural Seeds", description: "Unpolished natural white sesame.", sortOrder: 1 }
        ],
        specifications: [
            { groupName: "Details", specKey: "Weight", specValue: "500 grams", sortOrder: 1 }
        ],
        badges: []
    },
    {
        name: "Natural White Sesame Seeds - 1kg",
        slug: "natural-white-sesame-seeds-1kg",
        shortName: "Sesame Seeds 1kg",
        sku: "BAG-NTS-SES-1KG",
        barcode: "8901234501903",
        subCategoryId: 19,
        brand: "BlueAgle",
        shortDescription: "1kg bulk economy pack of cleaned white sesame seeds.",
        description: "Economical 1kg pack of BlueAgle Natural White Sesame Seeds. Perfect for festive sweet making and commercial recipes.",
        price: 460.00,
        mrp: 550.00,
        costPrice: 350.00,
        gstPercentage: 5.00,
        taxStatus: "Taxable",
        weight: "1kg",
        stock: 90,
        lowStockAlert: 10,
        minOrderQuantity: 1,
        maxOrderQuantity: 10,
        trackInventory: true,
        stockStatus: "In Stock",
        warehouseLocation: "C2-R03",
        images: [],
        videoUrl: null,
        isFeatured: false,
        isNewArrival: false,
        isBestSeller: false,
        isRecommended: false,
        isTrending: false,
        status: "Published",
        visibility: "Public",
        rating: 4.7,
        reviewCount: 33,
        viewCount: 490,
        tags: ["Sesame Seeds", "Til", "1kg"],
        ingredients: ["100% White Sesame Seeds"],
        benefits: ["Bulk pantry pack", "Cleaned seed quality"],
        usageInstructions: ["Keep sealed in a dry location"],
        deliveryTime: "2-4 Days",
        shippingMethod: "Standard Delivery",
        codAvailable: true,
        expressDelivery: true,
        returnEligible: true,
        replacementEligible: true,
        metaTitle: "Natural White Sesame Seeds 1kg | BlueAgle",
        metaDescription: "Buy BlueAgle White Sesame Seeds 1kg economy pack online.",
        metaKeywords: "sesame seeds 1kg, til 1kg, blueagle",
        customAttributes: { processing: "Machine Cleaned", packagingType: "Bulk Pouch", origin: "India" },
        highlights: [
            { icon: "FaTag", title: "Bulk Saver", description: "Best pricing for sweet makers & home bakers.", sortOrder: 1 }
        ],
        specifications: [
            { groupName: "Details", specKey: "Weight", specValue: "1000 grams (1kg)", sortOrder: 1 }
        ],
        badges: []
    },

    // Subcategory 20: Sunflower Seeds
    {
        name: "Premium Raw Sunflower Seeds - 250g",
        slug: "premium-raw-sunflower-seeds-250g",
        shortName: "Sunflower Seeds 250g",
        sku: "BAG-NTS-SFS-250G",
        barcode: "8901234502001",
        subCategoryId: 20,
        brand: "BlueAgle",
        shortDescription: "Cleaned raw dehulled sunflower seed kernels for snacking.",
        description: "BlueAgle Premium Raw Sunflower Seeds 250g are dehulled kernels offering mild nutty flavor and pleasant crunch. Great for snacking, salads, and smoothie bowls.",
        price: 145.00,
        mrp: 175.00,
        costPrice: 110.00,
        gstPercentage: 5.00,
        taxStatus: "Taxable",
        weight: "250g",
        stock: 100,
        lowStockAlert: 10,
        minOrderQuantity: 1,
        maxOrderQuantity: 20,
        trackInventory: true,
        stockStatus: "In Stock",
        warehouseLocation: "C3-R01",
        images: [],
        videoUrl: null,
        isFeatured: false,
        isNewArrival: true,
        isBestSeller: false,
        isRecommended: true,
        isTrending: false,
        status: "Published",
        visibility: "Public",
        rating: 4.7,
        reviewCount: 28,
        viewCount: 450,
        tags: ["Sunflower Seeds", "Raw Seeds", "Dehulled Kernels", "250g"],
        ingredients: ["100% Dehulled Sunflower Seed Kernels"],
        benefits: ["Dehulled and ready to eat", "Adds crunch to salads and breakfast bowls", "Natural seed snack"],
        usageInstructions: ["Eat raw or lightly roast for extra crunch", "Store in a cool dry place"],
        deliveryTime: "2-4 Days",
        shippingMethod: "Standard Delivery",
        codAvailable: true,
        expressDelivery: true,
        returnEligible: true,
        replacementEligible: true,
        metaTitle: "Premium Raw Sunflower Seeds 250g | BlueAgle Seeds",
        metaDescription: "Buy BlueAgle Premium Raw Sunflower Seeds 250g. Dehulled natural seed kernels for healthy snacking.",
        metaKeywords: "sunflower seeds 250g, dehulled sunflower kernels, blueagle seeds",
        customAttributes: { processing: "Dehulled & Cleaned", packagingType: "Pouch Pack", origin: "India" },
        highlights: [
            { icon: "FaSeedling", title: "Ready-to-Eat Kernels", description: "Dehulled seeds suitable for direct consumption and salad topping.", sortOrder: 1 }
        ],
        specifications: [
            { groupName: "Details", specKey: "Weight", specValue: "250 grams", sortOrder: 1 }
        ],
        badges: []
    },
    {
        name: "Premium Raw Sunflower Seeds - 500g",
        slug: "premium-raw-sunflower-seeds-500g",
        shortName: "Sunflower Seeds 500g",
        sku: "BAG-NTS-SFS-500G",
        barcode: "8901234502002",
        subCategoryId: 20,
        brand: "BlueAgle",
        shortDescription: "500g pack of cleaned dehulled raw sunflower seed kernels.",
        description: "BlueAgle Premium Raw Sunflower Seeds 500g provides raw dehulled kernels for daily culinary and dietary inclusion.",
        price: 275.00,
        mrp: 330.00,
        costPrice: 210.00,
        gstPercentage: 5.00,
        taxStatus: "Taxable",
        weight: "500g",
        stock: 110,
        lowStockAlert: 12,
        minOrderQuantity: 1,
        maxOrderQuantity: 20,
        trackInventory: true,
        stockStatus: "In Stock",
        warehouseLocation: "C3-R02",
        images: [],
        videoUrl: null,
        isFeatured: false,
        isNewArrival: false,
        isBestSeller: false,
        isRecommended: false,
        isTrending: false,
        status: "Published",
        visibility: "Public",
        rating: 4.8,
        reviewCount: 41,
        viewCount: 630,
        tags: ["Sunflower Seeds", "Raw Seeds", "500g"],
        ingredients: ["100% Dehulled Sunflower Kernels"],
        benefits: ["Cleaned & dehulled seed kernels", "Versatile culinary seed ingredient"],
        usageInstructions: ["Keep sealed in a cool place"],
        deliveryTime: "2-4 Days",
        shippingMethod: "Standard Delivery",
        codAvailable: true,
        expressDelivery: true,
        returnEligible: true,
        replacementEligible: true,
        metaTitle: "Premium Raw Sunflower Seeds 500g | BlueAgle",
        metaDescription: "Order BlueAgle Sunflower Seeds 500g pack. Cleaned raw seed kernels.",
        metaKeywords: "sunflower seeds 500g, sunflower kernels, blueagle",
        customAttributes: { processing: "Dehulled & Cleaned", packagingType: "Pouch Pack", origin: "India" },
        highlights: [
            { icon: "FaCheck", title: "Hygienic Packaging", description: "Sealed pouch pack for moisture protection.", sortOrder: 1 }
        ],
        specifications: [
            { groupName: "Details", specKey: "Weight", specValue: "500 grams", sortOrder: 1 }
        ],
        badges: []
    },

    // ─── CATEGORY 10: COMBOS & GIFT PACKS ──────────────────────────────────────
    // Subcategory 21: Cooking Oil Combo
    {
        name: "Everyday Cooking Oil Combo",
        slug: "everyday-cooking-oil-combo",
        shortName: "Everyday Cooking Combo",
        sku: "BAG-CMB-COC-1L2",
        barcode: "8901234502101",
        subCategoryId: 21,
        brand: "BlueAgle",
        shortDescription: "Essential kitchen twin pack: Groundnut Oil 1L + Sunflower Oil 1L.",
        description: "BlueAgle Everyday Cooking Oil Combo brings together 1 Liter of Cold Pressed Groundnut Oil and 1 Liter of Cold Pressed Sunflower Oil. Offers cooking versatility for both high-heat frying and light sautéing.",
        price: 645.00,
        mrp: 780.00,
        costPrice: 515.00,
        gstPercentage: 5.00,
        taxStatus: "Taxable",
        weight: "Combo Pack (2L Total)",
        stock: 75,
        lowStockAlert: 8,
        minOrderQuantity: 1,
        maxOrderQuantity: 10,
        trackInventory: true,
        stockStatus: "In Stock",
        warehouseLocation: "D1-R01",
        images: [],
        videoUrl: null,
        isFeatured: true,
        isNewArrival: false,
        isBestSeller: true,
        isRecommended: true,
        isTrending: true,
        status: "Published",
        visibility: "Public",
        rating: 4.9,
        reviewCount: 78,
        viewCount: 1850,
        tags: ["Combo Pack", "Groundnut Oil", "Sunflower Oil", "Cooking Oil Combo"],
        ingredients: ["1L Cold Pressed Groundnut Oil", "1L Cold Pressed Sunflower Oil"],
        benefits: ["Dual cooking versatility for frying and light dishes", "Special bundle pricing savings", "Both oils 100% unrefined"],
        usageInstructions: ["Use Groundnut oil for deep frying and Sunflower oil for light dishes", "Store in a cool dry pantry"],
        deliveryTime: "2-4 Days",
        shippingMethod: "Standard Delivery",
        codAvailable: true,
        expressDelivery: true,
        returnEligible: true,
        replacementEligible: true,
        metaTitle: "Everyday Cooking Oil Combo | BlueAgle Combo Packs",
        metaDescription: "Buy BlueAgle Everyday Cooking Oil Combo (Groundnut 1L + Sunflower 1L). Pure unrefined twin pack.",
        metaKeywords: "cooking oil combo, groundnut and sunflower oil pack, blueagle combo",
        customAttributes: { itemsIncluded: "1L Groundnut Oil + 1L Sunflower Oil", packagingType: "Twin Pack Box", origin: "India" },
        highlights: [
            { icon: "FaGift", title: "Twin Pack Savings", description: "Bundled combination discount for household kitchens.", sortOrder: 1 },
            { icon: "FaUtensils", title: "Kitchen Versatility", description: "Includes one robust frying oil and one light cooking oil.", sortOrder: 2 }
        ],
        specifications: [
            { groupName: "Combo Contents", specKey: "Item 1", specValue: "Cold Pressed Groundnut Oil 1L", sortOrder: 1 },
            { groupName: "Combo Contents", specKey: "Item 2", specValue: "Cold Pressed Sunflower Oil 1L", sortOrder: 2 }
        ],
        badges: [{ badgeText: "Best Combo", color: "#6366f1", icon: "FaStar", sortOrder: 1 }]
    },

    // Subcategory 22: Healthy Oil Combo
    {
        name: "Healthy Oil Combo Pack",
        slug: "healthy-oil-combo-pack",
        shortName: "Healthy Oil Combo",
        sku: "BAG-CMB-HOC-1L2",
        barcode: "8901234502201",
        subCategoryId: 22,
        brand: "BlueAgle",
        shortDescription: "Wellness twin pack: Cold Pressed Coconut Oil 1L + Cold Pressed Sesame Oil 1L.",
        description: "BlueAgle Healthy Oil Combo Pack combines 1L Cold Pressed Coconut Oil and 1L Cold Pressed Sesame Oil. Ideal for families seeking traditional unrefined cooking oils.",
        price: 870.00,
        mrp: 1050.00,
        costPrice: 690.00,
        gstPercentage: 5.00,
        taxStatus: "Taxable",
        weight: "Combo Pack (2L Total)",
        stock: 65,
        lowStockAlert: 8,
        minOrderQuantity: 1,
        maxOrderQuantity: 10,
        trackInventory: true,
        stockStatus: "In Stock",
        warehouseLocation: "D2-R01",
        images: [],
        videoUrl: null,
        isFeatured: true,
        isNewArrival: false,
        isBestSeller: true,
        isRecommended: true,
        isTrending: false,
        status: "Published",
        visibility: "Public",
        rating: 4.9,
        reviewCount: 64,
        viewCount: 1540,
        tags: ["Healthy Oil", "Coconut Oil", "Sesame Oil", "Combo Pack"],
        ingredients: ["1L Cold Pressed Coconut Oil", "1L Cold Pressed Sesame Oil"],
        benefits: ["Brings coastal & traditional aromas to your home", "100% unrefined cold pressed oils", "Bundle discount savings"],
        usageInstructions: ["Use coconut oil for curries/roasting and sesame oil for gravies/tempering"],
        deliveryTime: "2-4 Days",
        shippingMethod: "Standard Delivery",
        codAvailable: true,
        expressDelivery: true,
        returnEligible: true,
        replacementEligible: true,
        metaTitle: "Healthy Oil Combo Pack | BlueAgle",
        metaDescription: "Shop BlueAgle Healthy Oil Combo Pack (Coconut 1L + Sesame 1L). Pure traditional unrefined twin pack.",
        metaKeywords: "healthy oil combo, coconut and sesame oil pack, blueagle oil combo",
        customAttributes: { itemsIncluded: "1L Coconut Oil + 1L Sesame Oil", packagingType: "Combo Box", origin: "India" },
        highlights: [
            { icon: "FaHeart", title: "Traditional Wellness", description: "Pure copra coconut oil and aromatic sesame til oil twin pack.", sortOrder: 1 }
        ],
        specifications: [
            { groupName: "Combo Contents", specKey: "Item 1", specValue: "Cold Pressed Coconut Oil 1L", sortOrder: 1 },
            { groupName: "Combo Contents", specKey: "Item 2", specValue: "Cold Pressed Sesame Oil 1L", sortOrder: 2 }
        ],
        badges: [{ badgeText: "Wellness Pack", color: "#0d9488", icon: "FaHeart", sortOrder: 1 }]
    },

    // Subcategory 23: Traditional Oil Combo
    {
        name: "Traditional Oil Combo",
        slug: "traditional-oil-combo",
        shortName: "Traditional Trio Combo",
        sku: "BAG-CMB-TOC-1L3",
        barcode: "8901234502301",
        subCategoryId: 23,
        brand: "BlueAgle",
        shortDescription: "Heritage trio pack: Wood Pressed Groundnut 1L + Sesame 1L + Coconut 1L.",
        description: "BlueAgle Traditional Oil Combo brings you three 1-liter bottles of authentic Marachekku Wood Pressed Oils: Groundnut, Sesame, and Coconut. Extracted using wooden pestle chakkis without heat treatment.",
        price: 1290.00,
        mrp: 1550.00,
        costPrice: 1010.00,
        gstPercentage: 5.00,
        taxStatus: "Taxable",
        weight: "Combo Pack (3L Total)",
        stock: 55,
        lowStockAlert: 5,
        minOrderQuantity: 1,
        maxOrderQuantity: 5,
        trackInventory: true,
        stockStatus: "In Stock",
        warehouseLocation: "D3-R01",
        images: [],
        videoUrl: null,
        isFeatured: true,
        isNewArrival: false,
        isBestSeller: true,
        isRecommended: true,
        isTrending: true,
        status: "Published",
        visibility: "Public",
        rating: 5.0,
        reviewCount: 96,
        viewCount: 2350,
        tags: ["Traditional Oil", "Marachekku", "Trio Pack", "Wood Pressed Combo"],
        ingredients: ["1L Wood Pressed Groundnut Oil", "1L Wood Pressed Sesame Oil", "1L Wood Pressed Coconut Oil"],
        benefits: ["Complete 3-oil culinary arrangement", "100% Marachekku wooden pestle extracted", "Maximum bundle discount"],
        usageInstructions: ["Use appropriate oil based on recipe for authentic taste"],
        deliveryTime: "2-4 Days",
        shippingMethod: "Standard Delivery",
        codAvailable: true,
        expressDelivery: true,
        returnEligible: true,
        replacementEligible: true,
        metaTitle: "Traditional Oil Combo (3L Trio) | BlueAgle Marachekku Oils",
        metaDescription: "Buy BlueAgle Traditional Marachekku Trio Pack (Wood Pressed Groundnut + Sesame + Coconut 1L each).",
        metaKeywords: "traditional oil combo, marachekku trio pack, wood pressed oil bundle, blueagle",
        customAttributes: { itemsIncluded: "1L WP Groundnut + 1L WP Sesame + 1L WP Coconut", packagingType: "Master Box Pack", origin: "India" },
        highlights: [
            { icon: "FaTree", title: "Marachekku Trio", description: "Complete traditional oil mill package for authentic Indian kitchens.", sortOrder: 1 }
        ],
        specifications: [
            { groupName: "Combo Contents", specKey: "Item 1", specValue: "Wood Pressed Groundnut Oil 1L", sortOrder: 1 },
            { groupName: "Combo Contents", specKey: "Item 2", specValue: "Wood Pressed Sesame Oil 1L", sortOrder: 2 },
            { groupName: "Combo Contents", specKey: "Item 3", specValue: "Wood Pressed Coconut Oil 1L", sortOrder: 3 }
        ],
        badges: [{ badgeText: "Heritage Trio", color: "#b45309", icon: "FaCrown", sortOrder: 1 }]
    },

    // Subcategory 24: Festival Gift Pack
    {
        name: "Festival Oil Gift Pack",
        slug: "festival-oil-gift-pack",
        shortName: "Festival Gift Pack",
        sku: "BAG-CMB-FGP-BOX",
        barcode: "8901234502401",
        subCategoryId: 24,
        brand: "BlueAgle",
        shortDescription: "Premium gift box containing Traditional Gingelly Oil 500ml + Almond Oil 250ml + Sesame Seeds 250g.",
        description: "BlueAgle Festival Oil Gift Pack is an elegant gift box curated for festive occasions and celebrations. Includes 500ml Traditional Gingelly Oil, 250ml Cold Pressed Almond Oil, and 250g Natural White Sesame Seeds.",
        price: 790.00,
        mrp: 980.00,
        costPrice: 610.00,
        gstPercentage: 5.00,
        taxStatus: "Taxable",
        weight: "Gift Box",
        stock: 40,
        lowStockAlert: 5,
        minOrderQuantity: 1,
        maxOrderQuantity: 5,
        trackInventory: true,
        stockStatus: "In Stock",
        warehouseLocation: "D4-R01",
        images: [],
        videoUrl: null,
        isFeatured: true,
        isNewArrival: true,
        isBestSeller: false,
        isRecommended: true,
        isTrending: true,
        status: "Published",
        visibility: "Public",
        rating: 4.9,
        reviewCount: 38,
        viewCount: 940,
        tags: ["Gift Pack", "Festival Gift", "Almond Oil", "Gingelly Oil", "Gift Box"],
        ingredients: ["Gingelly Oil 500ml", "Almond Oil 250ml", "White Sesame Seeds 250g"],
        benefits: ["Beautifully packaged festive presentation", "Thoughtful natural gift for health and wellness", "Unrefined traditional oil standards"],
        usageInstructions: ["Perfect for festive gifting and family celebrations"],
        deliveryTime: "2-4 Days",
        shippingMethod: "Standard Delivery",
        codAvailable: true,
        expressDelivery: true,
        returnEligible: true,
        replacementEligible: true,
        metaTitle: "Festival Oil Gift Pack | BlueAgle Premium Gift Box",
        metaDescription: "Shop BlueAgle Festival Oil Gift Pack online. Thoughtful natural oil & seed gift box for festive celebrations.",
        metaKeywords: "festival oil gift pack, oil gift box, natural oils gift, blueagle gift pack",
        customAttributes: { itemsIncluded: "Gingelly 500ml + Almond 250ml + Sesame Seeds 250g", packagingType: "Festive Rigid Box", origin: "India" },
        highlights: [
            { icon: "FaGift", title: "Festive Presentation Box", description: "Curated premium box ready for auspicious gifting.", sortOrder: 1 }
        ],
        specifications: [
            { groupName: "Gift Contents", specKey: "Item 1", specValue: "Traditional Gingelly Oil 500ml", sortOrder: 1 },
            { groupName: "Gift Contents", specKey: "Item 2", specValue: "Cold Pressed Almond Oil 250ml", sortOrder: 2 },
            { groupName: "Gift Contents", specKey: "Item 3", specValue: "Natural White Sesame Seeds 250g", sortOrder: 3 }
        ],
        badges: [{ badgeText: "Gift Box", color: "#ec4899", icon: "FaGift", sortOrder: 1 }]
    },

    // Subcategory 25: Family Pack
    {
        name: "Family Oil Pack",
        slug: "family-oil-pack",
        shortName: "Family Mega Pack",
        sku: "BAG-CMB-FMP-CAN",
        barcode: "8901234502501",
        subCategoryId: 25,
        brand: "BlueAgle",
        shortDescription: "Mega household bundle: Wood Pressed Groundnut 5L Can + Wood Pressed Coconut 1L Bottle.",
        description: "BlueAgle Family Oil Pack is designed for monthly kitchen restocking. Combines a 5-Liter Wood Pressed Groundnut Oil jar with a 1-Liter Wood Pressed Coconut Oil bottle.",
        price: 2220.00,
        mrp: 2680.00,
        costPrice: 1750.00,
        gstPercentage: 5.00,
        taxStatus: "Taxable",
        weight: "6L Total",
        stock: 35,
        lowStockAlert: 5,
        minOrderQuantity: 1,
        maxOrderQuantity: 3,
        trackInventory: true,
        stockStatus: "In Stock",
        warehouseLocation: "D5-R01",
        images: [],
        videoUrl: null,
        isFeatured: false,
        isNewArrival: false,
        isBestSeller: true,
        isRecommended: true,
        isTrending: false,
        status: "Published",
        visibility: "Public",
        rating: 4.9,
        reviewCount: 44,
        viewCount: 820,
        tags: ["Family Pack", "Wood Pressed", "5L Groundnut", "1L Coconut", "Bulk Saver"],
        ingredients: ["5L Wood Pressed Groundnut Oil", "1L Wood Pressed Coconut Oil"],
        benefits: ["Mega savings for monthly household pantry restocking", "100% Marachekku wooden chekku milling", "Full kitchen oil coverage"],
        usageInstructions: ["Refill kitchen dispensers as needed"],
        deliveryTime: "3-5 Days",
        shippingMethod: "Heavy Cargo Delivery",
        codAvailable: true,
        expressDelivery: false,
        returnEligible: true,
        replacementEligible: true,
        metaTitle: "Family Oil Pack (5L + 1L) | BlueAgle",
        metaDescription: "Buy BlueAgle Family Oil Pack (Wood Pressed Groundnut 5L + Coconut 1L). Maximum bulk kitchen savings.",
        metaKeywords: "family oil pack, groundnut oil 5l coconut oil 1l, bulk cooking oil, blueagle",
        customAttributes: { itemsIncluded: "5L WP Groundnut Can + 1L WP Coconut Bottle", packagingType: "Bulk Combo", origin: "India" },
        highlights: [
            { icon: "FaBoxes", title: "Monthly Kitchen Solution", description: "Complete bulk oil combination for family cooking.", sortOrder: 1 }
        ],
        specifications: [
            { groupName: "Contents", specKey: "Item 1", specValue: "Wood Pressed Groundnut Oil 5L Can", sortOrder: 1 },
            { groupName: "Contents", specKey: "Item 2", specValue: "Wood Pressed Coconut Oil 1L Bottle", sortOrder: 2 }
        ],
        badges: [{ badgeText: "Mega Value", color: "#047857", icon: "FaTag", sortOrder: 1 }]
    }
];

async function seedDemoProducts() {
    console.log("=================================================");
    console.log("🌱 STARTING REALISTIC DEMO PRODUCT DATA SEEDING");
    console.log("=================================================");

    let createdCount = 0;
    let skippedCount = 0;
    let duplicateSKUs = 0;
    let highlightsCount = 0;
    let specsCount = 0;
    let badgesCount = 0;
    let errorsCount = 0;

    const reportTable = [];

    for (const prodData of PRODUCTS_DATA) {
        const { highlights, specifications, badges, ...productFields } = prodData;

        // Calculate offer percentage accurately if not explicitly fixed
        if (productFields.mrp && productFields.price) {
            const savings = productFields.mrp - productFields.price;
            productFields.offerPercentage = parseFloat(((savings / productFields.mrp) * 100).toFixed(2));
        }

        // STRICT IMAGE REQUIREMENT: MUST BE [] FOR ALL SEEDED PRODUCTS
        productFields.images = [];

        try {
            // Check idempotency by SKU
            const existing = await Product.findOne({ where: { sku: productFields.sku } });

            if (existing) {
                console.log(`⏩ [SKU EXISTS] Skipping ${productFields.sku} (${productFields.name})`);
                skippedCount++;
                duplicateSKUs++;
                
                // Fetch subcategory name for report table
                const subCat = await SubCategory.findByPk(existing.subCategoryId, { include: [Category] });
                reportTable.push({
                    Product: existing.name,
                    SKU: existing.sku,
                    Subcategory: subCat ? subCat.name : `SubCat #${existing.subCategoryId}`,
                    Category: subCat?.Category ? subCat.Category.name : 'Unknown',
                    Price: `₹${existing.price}`,
                    MRP: `₹${existing.mrp}`,
                    Stock: existing.stock,
                    Status: existing.status
                });
                continue;
            }

            // Create product record
            const createdProd = await Product.create(productFields);
            createdCount++;
            console.log(`✅ [CREATED] Product #${createdProd.id} | SKU: ${createdProd.sku} | Name: ${createdProd.name}`);

            // Add Highlights
            if (Array.isArray(highlights) && highlights.length > 0) {
                const hlRecords = highlights.map(h => ({
                    productId: createdProd.id,
                    icon: h.icon || 'FaLeaf',
                    title: h.title,
                    description: h.description,
                    sortOrder: h.sortOrder || 1
                }));
                await ProductHighlight.bulkCreate(hlRecords);
                highlightsCount += hlRecords.length;
            }

            // Add Specifications
            if (Array.isArray(specifications) && specifications.length > 0) {
                const specRecords = specifications.map(s => ({
                    productId: createdProd.id,
                    groupName: s.groupName || 'General',
                    specKey: s.specKey,
                    specValue: s.specValue,
                    sortOrder: s.sortOrder || 1
                }));
                await ProductSpecification.bulkCreate(specRecords);
                specsCount += specRecords.length;
            }

            // Add Badges
            if (Array.isArray(badges) && badges.length > 0) {
                const badgeRecords = badges.map(b => ({
                    productId: createdProd.id,
                    badgeText: b.badgeText,
                    color: b.color || '#ff3269',
                    icon: b.icon || null,
                    sortOrder: b.sortOrder || 1
                }));
                await ProductBadge.bulkCreate(badgeRecords);
                badgesCount += badgeRecords.length;
            }

            // Fetch subcategory for report table
            const subCat = await SubCategory.findByPk(createdProd.subCategoryId, { include: [Category] });

            reportTable.push({
                Product: createdProd.name,
                SKU: createdProd.sku,
                Subcategory: subCat ? subCat.name : `SubCat #${createdProd.subCategoryId}`,
                Category: subCat?.Category ? subCat.Category.name : 'Unknown',
                Price: `₹${createdProd.price}`,
                MRP: `₹${createdProd.mrp}`,
                Stock: createdProd.stock,
                Status: createdProd.status
            });

        } catch (err) {
            console.error(`❌ [ERROR] Failed to insert product ${productFields.name}:`, err.message);
            errorsCount++;
        }
    }

    console.log("\n=================================================");
    console.log("📊 SEEDING COMPLETE & SUMMARY REPORT");
    console.log("=================================================");
    console.log(`Categories used: 4 (IDs: 7, 8, 9, 10)`);
    console.log(`Subcategories used: 19 (IDs: 7 through 25)`);
    console.log(`Total Products Attempted: ${PRODUCTS_DATA.length}`);
    console.log(`Products Created: ${createdCount}`);
    console.log(`Products Skipped: ${skippedCount}`);
    console.log(`Duplicate SKUs: ${duplicateSKUs}`);
    console.log(`Products with Images: 0`);
    console.log(`Products with Empty Images ([]): ${createdCount + skippedCount}`);
    console.log(`Highlights Created: ${highlightsCount}`);
    console.log(`Specifications Created: ${specsCount}`);
    console.log(`Badges Created: ${badgesCount}`);
    console.log(`Certifications Created: 0`);
    console.log(`Nutrition Records Created: 0`);
    console.log(`SEO Fields Populated: ${createdCount}`);
    console.log(`Errors: ${errorsCount}`);
    console.log("=================================================\n");

    console.table(reportTable);

    process.exit(0);
}

seedDemoProducts();
