const { DataTypes } = require('sequelize');
const sequelize = require('../config/database');

const SeoSetting = sequelize.define('SeoSetting', {
    id: {
        type: DataTypes.INTEGER,
        primaryKey: true,
        autoIncrement: true,
    },
    pageKey: {
        type: DataTypes.STRING,
        allowNull: false,
        unique: true,
    },
    pageName: {
        type: DataTypes.STRING,
        allowNull: false,
    },
    pageType: {
        type: DataTypes.STRING,
        allowNull: false,
        defaultValue: 'static', // static, product, category, subcategory, blog, CMS, custom
    },
    route: {
        type: DataTypes.STRING,
        allowNull: false,
    },
    title: {
        type: DataTypes.STRING,
        allowNull: true,
    },
    metaDescription: {
        type: DataTypes.TEXT,
        allowNull: true,
    },
    metaKeywords: {
        type: DataTypes.TEXT,
        allowNull: true,
    },
    canonicalUrl: {
        type: DataTypes.STRING,
        allowNull: true,
    },
    robots: {
        type: DataTypes.STRING,
        allowNull: false,
        defaultValue: 'index, follow',
    },
    author: {
        type: DataTypes.STRING,
        allowNull: true,
    },
    language: {
        type: DataTypes.STRING,
        allowNull: false,
        defaultValue: 'en',
    },
    viewport: {
        type: DataTypes.STRING,
        allowNull: false,
        defaultValue: 'width=device-width, initial-scale=1.0',
    },
    themeColor: {
        type: DataTypes.STRING,
        allowNull: true,
        defaultValue: '#3c006b',
    },
    favicon: {
        type: DataTypes.STRING,
        allowNull: true,
    },
    // Open Graph
    ogTitle: {
        type: DataTypes.STRING,
        allowNull: true,
    },
    ogDescription: {
        type: DataTypes.TEXT,
        allowNull: true,
    },
    ogImage: {
        type: DataTypes.STRING,
        allowNull: true,
    },
    ogUrl: {
        type: DataTypes.STRING,
        allowNull: true,
    },
    ogType: {
        type: DataTypes.STRING,
        allowNull: false,
        defaultValue: 'website',
    },
    // Twitter Card
    twitterCard: {
        type: DataTypes.STRING,
        allowNull: false,
        defaultValue: 'summary_large_image',
    },
    twitterTitle: {
        type: DataTypes.STRING,
        allowNull: true,
    },
    twitterDescription: {
        type: DataTypes.TEXT,
        allowNull: true,
    },
    twitterImage: {
        type: DataTypes.STRING,
        allowNull: true,
    },
    // JSON Data Structures
    structuredData: {
        type: DataTypes.JSON,
        allowNull: true,
    },
    alternateLanguages: {
        type: DataTypes.JSON,
        allowNull: true,
    },
    customHeadTags: {
        type: DataTypes.TEXT,
        allowNull: true,
    },
    customMetaTags: {
        type: DataTypes.TEXT,
        allowNull: true,
    },
    // Sitemap & Crawling Flags
    priority: {
        type: DataTypes.FLOAT,
        allowNull: false,
        defaultValue: 0.8,
    },
    changeFrequency: {
        type: DataTypes.STRING,
        allowNull: false,
        defaultValue: 'weekly', // always, hourly, daily, weekly, monthly, yearly, never
    },
    isIndexed: {
        type: DataTypes.BOOLEAN,
        allowNull: false,
        defaultValue: true,
    },
    isActive: {
        type: DataTypes.BOOLEAN,
        allowNull: false,
        defaultValue: true,
    },
    createdBy: {
        type: DataTypes.STRING,
        allowNull: true,
    },
    updatedBy: {
        type: DataTypes.STRING,
        allowNull: true,
    },
    // ─── Auto-Sync Tracking Flags ────────────────────────────────────────────
    isAutoGenerated: {
        type: DataTypes.BOOLEAN,
        allowNull: false,
        defaultValue: false,
        comment: 'True when record was created by the auto-SEO sync engine',
    },
    isManuallyEdited: {
        type: DataTypes.BOOLEAN,
        allowNull: false,
        defaultValue: false,
        comment: 'True once an admin manually edits any field. Prevents auto-overwrite.',
    },
    lastSyncedAt: {
        type: DataTypes.DATE,
        allowNull: true,
        comment: 'Timestamp of the last auto-sync that touched this record',
    },
}, {
    timestamps: true,
    tableName: 'seo_settings'
});

module.exports = SeoSetting;
